const express = require("express");
const router = express.Router();
const coursesController = require("../controllers/courses.controller");
const {
  authenticateToken,
  isSystemAdmin,
  requireRole,
} = require("../middleware");

const canManageCourse = requireRole("system_admin", "school_admin", "teacher");

router.get("/", authenticateToken, coursesController.getAllCourses);
router.get(
  "/learner/badges",
  authenticateToken,
  coursesController.getLearnerBadges,
);
router.post(
  "/",
  authenticateToken,
  isSystemAdmin,
  coursesController.createCourse,
);
router.get(
  "/:id/learning-overview",
  authenticateToken,
  coursesController.getLearningOverview,
);
router.get(
  "/:courseId/modules/:moduleId/learn",
  authenticateToken,
  coursesController.getModuleLearning,
);
router.get(
  "/:courseId/modules/:moduleId/pdf",
  authenticateToken,
  canManageCourse,
  coursesController.downloadModulePdf,
);
router.post(
  "/modules/:moduleId/feedback",
  authenticateToken,
  coursesController.submitModuleFeedback,
);
router.get(
  "/modules/:moduleId/feedback-summary",
  authenticateToken,
  canManageCourse,
  coursesController.getModuleFeedbackSummary,
);
router.get(
  "/templates/:templateId/feedback-report",
  authenticateToken,
  isSystemAdmin,
  coursesController.getTemplateFeedbackReport,
);
router.get(
  "/:courseId/feedback-report",
  authenticateToken,
  canManageCourse,
  coursesController.getCourseFeedbackReport,
);
router.post(
  "/feedback/:feedbackId/reveal",
  authenticateToken,
  isSystemAdmin,
  coursesController.revealModuleFeedbackIdentity,
);
router.post(
  "/activities/:activityId/progress",
  authenticateToken,
  coursesController.updateActivityProgress,
);
router.get(
  "/activities/:activityId/discussion",
  authenticateToken,
  coursesController.getActivityDiscussion,
);
router.post(
  "/activities/:activityId/discussion/replies",
  authenticateToken,
  coursesController.addDiscussionReply,
);
router.post(
  "/activities/:activityId/quiz-attempts",
  authenticateToken,
  coursesController.submitQuiz,
);
router.post(
  "/activities/:activityId/submissions",
  authenticateToken,
  coursesController.submitActivityWork,
);
router.get(
  "/activities/:activityId/review",
  authenticateToken,
  canManageCourse,
  coursesController.getActivityReview,
);
router.put(
  "/activities/:activityId/learners/:learnerId/grade",
  authenticateToken,
  canManageCourse,
  coursesController.gradeActivityForLearner,
);
router.post(
  "/activity-images",
  authenticateToken,
  canManageCourse,
  coursesController.uploadActivityImage,
);
router.post(
  "/submission-files",
  authenticateToken,
  coursesController.uploadSubmissionFile,
);
router.post(
  "/:id/modules",
  authenticateToken,
  canManageCourse,
  coursesController.createModule,
);
router.get(
  "/:id/availability-overrides",
  authenticateToken,
  canManageCourse,
  coursesController.listAvailabilityOverrides,
);
router.post(
  "/:id/availability-overrides",
  authenticateToken,
  canManageCourse,
  coursesController.createAvailabilityOverride,
);
router.delete(
  "/availability-overrides/:overrideId",
  authenticateToken,
  canManageCourse,
  coursesController.revokeAvailabilityOverride,
);
router.post(
  "/:id/sync-template",
  authenticateToken,
  requireRole("system_admin", "school_admin"),
  coursesController.syncSchoolCourse,
);
router.post(
  "/:id/rollback-template",
  authenticateToken,
  requireRole("system_admin", "school_admin"),
  coursesController.rollbackSchoolCourse,
);
router.put(
  "/modules/:moduleId",
  authenticateToken,
  canManageCourse,
  coursesController.updateModule,
);
router.delete(
  "/modules/:moduleId",
  authenticateToken,
  canManageCourse,
  coursesController.deleteModule,
);
router.post(
  "/modules/:moduleId/activities",
  authenticateToken,
  canManageCourse,
  coursesController.createActivity,
);
router.put(
  "/modules/:moduleId/activities/order",
  authenticateToken,
  canManageCourse,
  coursesController.reorderActivities,
);
router.put(
  "/activities/:activityId",
  authenticateToken,
  canManageCourse,
  coursesController.updateActivity,
);
router.delete(
  "/activities/:activityId",
  authenticateToken,
  canManageCourse,
  coursesController.deleteActivity,
);
router.get("/:id", authenticateToken, coursesController.getCourseById);
router.put(
  "/:id",
  authenticateToken,
  isSystemAdmin,
  coursesController.updateCourse,
);
router.delete(
  "/:id",
  authenticateToken,
  isSystemAdmin,
  coursesController.deleteCourse,
);

module.exports = router;
