-- Generated by scripts/mysql-migration/translate-schema.js. Do not edit.
-- Source: src/database/schema.sql
--
-- Row level security is intentionally absent: those policies guarded the
-- Supabase REST endpoint only, and the application already authorises every
-- request itself. MySQL has no equivalent and none is needed.

SET FOREIGN_KEY_CHECKS = 0;
-- Schools table
CREATE TABLE IF NOT EXISTS schools (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255),
  phone VARCHAR(50),
  address TEXT,
  logo_url TEXT,
  allow_self_registration TINYINT(1) DEFAULT FALSE,
  is_independent_school TINYINT(1) DEFAULT FALSE,
  report_card_settings JSON DEFAULT ('{"show_weekly_typing":true,"show_weekly_quizzes":true,"show_active_courses":true,"show_competitions":true,"show_badges":true,"show_teacher_feedback":true}'),
  is_active TINYINT(1) DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schools ADD COLUMN is_independent_school TINYINT(1) DEFAULT FALSE;

ALTER TABLE schools ADD COLUMN report_card_settings JSON DEFAULT ('{"show_weekly_typing":true,"show_weekly_quizzes":true,"show_active_courses":true,"show_competitions":true,"show_badges":true,"show_teacher_feedback":true}');

INSERT INTO schools (name, code, email, allow_self_registration, is_independent_school, is_active)
VALUES ('eduClub Independent Learners', 'EDUCLUB-INDEPENDENT', 'support@educlub.co.ke', true, true, true)
ON DUPLICATE KEY UPDATE name = VALUES(name),
    allow_self_registration = true,
    is_independent_school = true,
    is_active = true,
    updated_at = CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  full_name VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL CHECK (role IN ('system_admin', 'school_admin', 'teacher', 'learner')),
  school_id INT,
  username VARCHAR(50) UNIQUE,
  mfa_enabled TINYINT(1) DEFAULT FALSE,
  mfa_secret VARCHAR(255),
  mfa_code VARCHAR(10),
  mfa_code_expires_at DATETIME,
  force_password_reset TINYINT(1) DEFAULT TRUE,
  is_active TINYINT(1) DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL
);

ALTER TABLE users DROP CHECK users_role_check;

ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('system_admin', 'school_admin', 'teacher', 'learner'));

CREATE TABLE IF NOT EXISTS school_admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  school_id INT,
  is_primary TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, school_id),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learners (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  school_id INT,
  full_name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  grade VARCHAR(50),
  stream VARCHAR(50),
  term VARCHAR(50),
  academic_year INT,
  next_grade VARCHAR(50),
  next_term VARCHAR(50),
  is_active TINYINT(1) DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

ALTER TABLE learners ADD COLUMN user_id INT;

ALTER TABLE learners
  ADD FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE learners ADD COLUMN graduation_status VARCHAR(20) NOT NULL DEFAULT 'active';

ALTER TABLE schools ADD COLUMN grades_config JSON DEFAULT ('[]');

ALTER TABLE schools ADD COLUMN streams_config JSON DEFAULT ('[]');

ALTER TABLE audit_logs ADD COLUMN user_agent TEXT;

ALTER TABLE learners DROP CHECK learners_graduation_status_check;

ALTER TABLE learners ADD CONSTRAINT learners_graduation_status_check
  CHECK (graduation_status IN ('active', 'graduated'));

ALTER TABLE learners ADD COLUMN graduated_at DATETIME;

ALTER TABLE learners ADD COLUMN graduated_by_user_id INT;

ALTER TABLE learners
  ADD FOREIGN KEY (graduated_by_user_id) REFERENCES users(id) ON DELETE SET NULL;

ALTER TABLE learners ADD COLUMN graduation_note TEXT;

CREATE TABLE IF NOT EXISTS academic_years (
  id INT AUTO_INCREMENT PRIMARY KEY,
  year INT UNIQUE NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date > start_date)
);

CREATE TABLE IF NOT EXISTS terms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  academic_year_id INT,
  name VARCHAR(50) NOT NULL,
  term_type VARCHAR(50) DEFAULT 'regular' CHECK (term_type IN ('regular', 'crash_course', 'holiday_program', 'intensive', 'other')),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  is_active TINYINT(1) DEFAULT FALSE,
  total_weeks INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date > start_date),
  FOREIGN KEY (academic_year_id) REFERENCES academic_years(id) ON DELETE CASCADE
);

ALTER TABLE terms
  ADD COLUMN active_term_type VARCHAR(50)
    GENERATED ALWAYS AS (IF(is_active = 1, term_type, NULL)) STORED;

CREATE UNIQUE INDEX idx_terms_one_active_per_type ON terms(active_term_type);

CREATE INDEX idx_terms_year_name_type
  ON terms(academic_year_id, name, term_type);

CREATE TABLE IF NOT EXISTS term_weeks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  term_id INT,
  week_number INT NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(term_id, week_number),
  CHECK (end_date > start_date),
  FOREIGN KEY (term_id) REFERENCES terms(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS courses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  school_id INT,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(80),
  description TEXT,
  target_level VARCHAR(80),
  image_url TEXT,
  estimated_weeks INT,
  learning_objectives JSON DEFAULT ('[]'),
  certificate_enabled TINYINT(1) DEFAULT FALSE,
  independent_price_amount DECIMAL(12, 2) DEFAULT 0,
  independent_currency VARCHAR(10) DEFAULT 'KES',
  course_category VARCHAR(50) DEFAULT 'general' CHECK (course_category IN ('general', 'weekly_typing', 'weekly_quiz')),
  is_active TINYINT(1) DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL
);

ALTER TABLE courses ADD COLUMN school_id INT;

ALTER TABLE courses
  ADD FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;

ALTER TABLE courses ADD COLUMN code VARCHAR(80);

ALTER TABLE courses ADD COLUMN target_level VARCHAR(80);

ALTER TABLE courses ADD COLUMN image_url TEXT;

ALTER TABLE courses ADD COLUMN estimated_weeks INT;

ALTER TABLE courses ADD COLUMN learning_objectives JSON DEFAULT ('[]');

ALTER TABLE courses ADD COLUMN certificate_enabled TINYINT(1) DEFAULT FALSE;

ALTER TABLE courses ADD COLUMN independent_price_amount DECIMAL(12, 2) DEFAULT 0;

ALTER TABLE courses ADD COLUMN independent_currency VARCHAR(10) DEFAULT 'KES';

ALTER TABLE courses ADD COLUMN course_category VARCHAR(50) DEFAULT 'general';

ALTER TABLE courses DROP CHECK courses_course_category_check;

ALTER TABLE courses ADD CONSTRAINT courses_course_category_check
  CHECK (course_category IN ('general', 'weekly_typing', 'weekly_quiz'));

CREATE UNIQUE INDEX idx_courses_school_code
  ON courses(school_id, code)
  /* predicate dropped: WHERE code IS NOT NULL */;

CREATE TABLE IF NOT EXISTS course_templates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  code VARCHAR(80),
  description TEXT,
  target_level VARCHAR(80),
  image_url TEXT,
  estimated_weeks INT,
  learning_objectives JSON DEFAULT ('[]'),
  certificate_enabled TINYINT(1) DEFAULT FALSE,
  independent_price_amount DECIMAL(12, 2) DEFAULT 0,
  independent_currency VARCHAR(10) DEFAULT 'KES',
  course_category VARCHAR(50) DEFAULT 'general'
    CHECK (course_category IN ('general', 'weekly_typing', 'weekly_quiz')),
  version INT DEFAULT 1,
  is_active TINYINT(1) DEFAULT TRUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_course_templates_code
  ON course_templates(code)
  /* predicate dropped: WHERE code IS NOT NULL */;

ALTER TABLE course_templates ADD COLUMN independent_price_amount DECIMAL(12, 2) DEFAULT 0;

ALTER TABLE course_templates ADD COLUMN independent_currency VARCHAR(10) DEFAULT 'KES';

CREATE TABLE IF NOT EXISTS course_template_modules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_id INT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  learning_outcomes JSON DEFAULT ('[]'),
  position INT NOT NULL DEFAULT 1,
  is_published TINYINT(1) DEFAULT FALSE,
  unlock_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(template_id, position),
  FOREIGN KEY (template_id) REFERENCES course_templates(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS course_template_activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_module_id INT,
  title VARCHAR(255) NOT NULL,
  activity_type VARCHAR(50) NOT NULL
    CHECK (activity_type IN ('lesson', 'quiz', 'assignment', 'discussion', 'coding', 'typing', 'project', 'reflection')),
  content JSON DEFAULT ('{}'),
  points DECIMAL(8, 2) DEFAULT 0,
  position INT NOT NULL DEFAULT 1,
  is_required TINYINT(1) DEFAULT TRUE,
  availability_mode VARCHAR(20) NOT NULL DEFAULT 'required'
    CHECK (availability_mode IN ('required', 'try_more')),
  completion_rule VARCHAR(50) DEFAULT 'manual'
    CHECK (completion_rule IN ('manual', 'viewed', 'scrolled', 'submitted', 'graded', 'score_at_least')),
  pass_score DECIMAL(8, 2),
  is_published TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(template_module_id, position),
  FOREIGN KEY (template_module_id) REFERENCES course_template_modules(id) ON DELETE CASCADE
);

ALTER TABLE course_template_activities
  ADD COLUMN availability_mode VARCHAR(20) NOT NULL DEFAULT 'required';

ALTER TABLE course_template_activities
  DROP CHECK course_template_activities_availability_mode_check;

ALTER TABLE course_template_activities
  ADD CONSTRAINT course_template_activities_availability_mode_check
  CHECK (availability_mode IN ('required', 'try_more'));

ALTER TABLE courses ADD COLUMN template_id INT;

ALTER TABLE courses
  ADD FOREIGN KEY (template_id) REFERENCES course_templates(id) ON DELETE SET NULL;

ALTER TABLE courses ADD COLUMN template_version INT;

ALTER TABLE courses ADD COLUMN school_version INT DEFAULT 1;

ALTER TABLE courses ADD COLUMN last_template_sync_at DATETIME;

CREATE TABLE IF NOT EXISTS course_teacher_assignments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  teacher_user_id INT NOT NULL,
  assigned_by_user_id INT,
  notes TEXT,
  is_active TINYINT(1) NOT NULL DEFAULT TRUE,
  assigned_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deallocated_at DATETIME,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(course_id, teacher_user_id),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (assigned_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS course_update_requests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  teacher_user_id INT NOT NULL,
  template_version INT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'reviewed', 'dismissed')),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  reviewed_at DATETIME,
  reviewed_by_user_id INT,
  UNIQUE(course_id, teacher_user_id, template_version),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (teacher_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (reviewed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_course_teacher_assignments_teacher_active
  ON course_teacher_assignments(teacher_user_id, is_active, course_id);

CREATE INDEX idx_course_teacher_assignments_course_active
  ON course_teacher_assignments(course_id, is_active, teacher_user_id);

CREATE INDEX idx_course_update_requests_course_status
  ON course_update_requests(course_id, status, template_version);

CREATE TABLE IF NOT EXISTS course_modules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT,
  template_module_id INT,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  learning_outcomes JSON DEFAULT ('[]'),
  position INT NOT NULL DEFAULT 1,
  is_published TINYINT(1) DEFAULT FALSE,
  unlock_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(course_id, position),
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (template_module_id) REFERENCES course_template_modules(id) ON DELETE SET NULL
);

ALTER TABLE course_modules ADD COLUMN template_module_id INT;

ALTER TABLE course_modules
  ADD FOREIGN KEY (template_module_id) REFERENCES course_template_modules(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS learning_activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module_id INT,
  template_activity_id INT,
  title VARCHAR(255) NOT NULL,
  activity_type VARCHAR(50) NOT NULL
    CHECK (activity_type IN ('lesson', 'quiz', 'assignment', 'discussion', 'coding', 'typing', 'project', 'reflection')),
  content JSON DEFAULT ('{}'),
  points DECIMAL(8, 2) DEFAULT 0,
  position INT NOT NULL DEFAULT 1,
  is_required TINYINT(1) DEFAULT TRUE,
  completion_rule VARCHAR(50) DEFAULT 'manual'
    CHECK (completion_rule IN ('manual', 'viewed', 'scrolled', 'submitted', 'graded', 'score_at_least')),
  pass_score DECIMAL(8, 2),
  is_published TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(module_id, position),
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE,
  FOREIGN KEY (template_activity_id) REFERENCES course_template_activities(id) ON DELETE SET NULL
);

ALTER TABLE learning_activities ADD COLUMN template_activity_id INT;

ALTER TABLE learning_activities
  ADD FOREIGN KEY (template_activity_id) REFERENCES course_template_activities(id) ON DELETE SET NULL;

ALTER TABLE learning_activities
  ADD COLUMN availability_mode VARCHAR(20) NOT NULL DEFAULT 'required';

ALTER TABLE learning_activities
  DROP CHECK learning_activities_availability_mode_check;

ALTER TABLE learning_activities
  ADD CONSTRAINT learning_activities_availability_mode_check
  CHECK (availability_mode IN ('required', 'try_more'));

INSERT INTO course_templates (
  name, code, description, target_level, image_url, estimated_weeks,
  learning_objectives, certificate_enabled, course_category, is_active
)
SELECT
  c.name, c.code, c.description, c.target_level, c.image_url, c.estimated_weeks,
  c.learning_objectives, c.certificate_enabled, c.course_category, c.is_active
FROM courses c
WHERE c.school_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM course_templates t
    WHERE (c.code IS NOT NULL AND t.code = c.code)
       OR (c.code IS NULL AND t.code IS NULL AND t.name = c.name)
  );

INSERT INTO course_template_modules (
  template_id, title, description, learning_outcomes, position, is_published, unlock_at
)
SELECT
  t.id, cm.title, cm.description, cm.learning_outcomes, cm.position, cm.is_published, cm.unlock_at
FROM course_modules cm
JOIN courses c ON c.id = cm.course_id
JOIN course_templates t ON (
  (c.code IS NOT NULL AND t.code = c.code)
  OR (c.code IS NULL AND t.code IS NULL AND t.name = c.name)
)
WHERE c.school_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM course_template_modules tm
    WHERE tm.template_id = t.id
      AND tm.position = cm.position
  );

INSERT INTO course_template_activities (
  template_module_id, title, activity_type, content, points, position,
  is_required, availability_mode, completion_rule, pass_score, is_published
)
SELECT
  tm.id, la.title, la.activity_type, la.content, la.points, la.position,
  la.is_required, COALESCE(la.availability_mode, 'required'),
  la.completion_rule, la.pass_score, la.is_published
FROM learning_activities la
JOIN course_modules cm ON cm.id = la.module_id
JOIN courses c ON c.id = cm.course_id
JOIN course_templates t ON (
  (c.code IS NOT NULL AND t.code = c.code)
  OR (c.code IS NULL AND t.code IS NULL AND t.name = c.name)
)
JOIN course_template_modules tm
  ON tm.template_id = t.id
 AND tm.position = cm.position
WHERE c.school_id IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM course_template_activities ta
    WHERE ta.template_module_id = tm.id
      AND ta.position = la.position
  );

CREATE TABLE IF NOT EXISTS activity_progress (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  activity_id INT,
  status VARCHAR(50) DEFAULT 'not_started'
    CHECK (status IN ('not_started', 'started', 'in_progress', 'submitted', 'completed', 'graded')),
  score DECIMAL(8, 2),
  opened_at DATETIME,
  completed_at DATETIME,
  graded_at DATETIME,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, activity_id),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_submissions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  activity_id INT,
  submission_type VARCHAR(50) DEFAULT 'text'
    CHECK (submission_type IN ('text', 'file', 'image', 'link', 'code', 'project')),
  content JSON DEFAULT ('{}'),
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(50) DEFAULT 'submitted'
    CHECK (status IN ('submitted', 'returned', 'graded')),
  UNIQUE(learner_id, activity_id),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS activity_grades (
  id INT AUTO_INCREMENT PRIMARY KEY,
  submission_id INT,
  learner_id INT,
  activity_id INT,
  score DECIMAL(8, 2) CHECK (score >= 0),
  question_marks JSON DEFAULT ('{}'),
  performance_level VARCHAR(80),
  teacher_remarks TEXT,
  graded_by_user_id INT,
  graded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, activity_id),
  FOREIGN KEY (submission_id) REFERENCES activity_submissions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE,
  FOREIGN KEY (graded_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS school_module_schedules (
  id INT AUTO_INCREMENT PRIMARY KEY,
  module_id INT NOT NULL,
  term_id INT NOT NULL,
  week_number INT NOT NULL CHECK (week_number > 0),
  opens_at DATETIME NOT NULL,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(module_id),
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE,
  FOREIGN KEY (term_id) REFERENCES terms(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS learning_availability_overrides (
  id INT AUTO_INCREMENT PRIMARY KEY,
  school_id INT NOT NULL,
  course_id INT NOT NULL,
  module_id INT,
  activity_id INT,
  scope_type VARCHAR(20) NOT NULL
    CHECK (scope_type IN ('class', 'learners', 'learner')),
  target_learner_id INT,
  target_learner_ids JSON DEFAULT ('[]'),
  target_grade VARCHAR(50),
  target_stream VARCHAR(50),
  reason TEXT NOT NULL,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  revoked_at DATETIME,
  CHECK (module_id IS NOT NULL OR activity_id IS NOT NULL),
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE,
  FOREIGN KEY (target_learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS learner_module_badges (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT NOT NULL,
  course_id INT NOT NULL,
  module_id INT NOT NULL,
  tier VARCHAR(20) NOT NULL
    CHECK (tier IN ('completion', 'bronze', 'silver', 'gold')),
  score_percent DECIMAL(8, 4) NOT NULL CHECK (score_percent BETWEEN 0 AND 100),
  badge_name VARCHAR(255),
  awarded_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, module_id),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS module_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT NOT NULL,
  school_id INT NOT NULL,
  course_id INT NOT NULL,
  module_id INT NOT NULL,
  module_version INT NOT NULL DEFAULT 1,
  rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, module_id),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (module_id) REFERENCES course_modules(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback_identity_audits (
  id INT AUTO_INCREMENT PRIMARY KEY,
  feedback_id INT NOT NULL,
  accessed_by_user_id INT,
  reason TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (feedback_id) REFERENCES module_feedback(id) ON DELETE CASCADE,
  FOREIGN KEY (accessed_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO learner_module_badges (
  learner_id, course_id, module_id, tier, score_percent, badge_name,
  awarded_at, updated_at
)
SELECT
  completed.learner_id,
  completed.course_id,
  completed.module_id,
  CASE
    WHEN completed.score_percent > 90 THEN 'gold'
    WHEN completed.score_percent > 80 THEN 'silver'
    WHEN completed.score_percent >= 71 THEN 'bronze'
    ELSE 'completion'
  END,
  completed.score_percent,
  completed.badge_name,
  NOW(),
  NOW()
FROM (
  SELECT
    ap.learner_id,
    cm.course_id,
    cm.id AS module_id,
    COALESCE(AVG(CASE WHEN ap.score IS NOT NULL THEN ap.score END), 100) AS score_percent,
    COALESCE(MAX(la.content->>'$.module_badge.name'), cm.title) AS badge_name,
    COUNT(CASE WHEN COALESCE(la.availability_mode, 'required') = 'required'
        AND la.is_published = true THEN la.id END) AS required_total,
    COUNT(CASE WHEN COALESCE(la.availability_mode, 'required') = 'required'
        AND la.is_published = true
        AND ap.status IN ('completed', 'graded') THEN ap.id END) AS required_done
  FROM course_modules cm
  JOIN learning_activities la ON la.module_id = cm.id
  JOIN activity_progress ap ON ap.activity_id = la.id
  GROUP BY ap.learner_id, cm.course_id, cm.id
) completed
WHERE completed.required_total > 0
  AND completed.required_done >= completed.required_total
ON DUPLICATE KEY UPDATE tier = VALUES(tier),
  score_percent = VALUES(score_percent),
  badge_name = VALUES(badge_name),
  updated_at = NOW();

CREATE TABLE IF NOT EXISTS quiz_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  activity_id INT,
  question_type VARCHAR(50) NOT NULL CHECK (question_type IN ('multiple_choice', 'multi_select', 'true_false', 'short_answer', 'matching', 'ordering')),
  prompt TEXT NOT NULL,
  image_url TEXT,
  options JSON DEFAULT ('[]'),
  correct_answer JSON DEFAULT ('{}'),
  points DECIMAL(8, 2) DEFAULT 1,
  position INT NOT NULL DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE
);

ALTER TABLE quiz_questions
  ADD COLUMN image_url TEXT;

ALTER TABLE quiz_questions
  DROP CHECK quiz_questions_question_type_check;

ALTER TABLE quiz_questions
  ADD CONSTRAINT quiz_questions_question_type_check
  CHECK (question_type IN ('multiple_choice', 'multi_select', 'true_false', 'short_answer', 'matching', 'ordering'));

CREATE TABLE IF NOT EXISTS quiz_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  activity_id INT,
  attempt_number INT NOT NULL DEFAULT 1,
  answers JSON DEFAULT ('{}'),
  score DECIMAL(8, 2) DEFAULT 0,
  feedback JSON DEFAULT ('{}'),
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, activity_id, attempt_number),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS discussions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  activity_id INT,
  prompt TEXT NOT NULL,
  allow_peer_replies TINYINT(1) DEFAULT TRUE,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (activity_id) REFERENCES learning_activities(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS discussion_replies (
  id INT AUTO_INCREMENT PRIMARY KEY,
  discussion_id INT,
  learner_id INT,
  author_user_id INT,
  parent_reply_id INT,
  body TEXT NOT NULL,
  is_hidden TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (discussion_id) REFERENCES discussions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (author_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (parent_reply_id) REFERENCES discussion_replies(id) ON DELETE CASCADE
);

ALTER TABLE discussion_replies ADD COLUMN author_user_id INT;

ALTER TABLE discussion_replies
  ADD FOREIGN KEY (author_user_id) REFERENCES users(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS course_allocations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  course_id INT,
  term VARCHAR(50),
  academic_year INT,
  status VARCHAR(50) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'completed', 'dropped')),
  access_level VARCHAR(20) DEFAULT 'paid' CHECK (access_level IN ('preview', 'paid', 'grant', 'scholarship')),
  preview_activity_limit INT DEFAULT 0,
  paid_at DATETIME,
  payment_reference VARCHAR(100),
  allocated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME,
  start_date DATE,
  end_date DATE,
  UNIQUE(learner_id, course_id, term, academic_year),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS grades_cache (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  course_id INT,
  term VARCHAR(50) NOT NULL,
  academic_year INT NOT NULL,
  UNIQUE(learner_id, course_id, term, academic_year),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS progress_cache (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  course_id INT,
  term VARCHAR(50) NOT NULL,
  academic_year INT NOT NULL,
  progress_data JSON NOT NULL,
  last_synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, course_id, term, academic_year),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_marks (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  week_number INT NOT NULL,
  term VARCHAR(50) NOT NULL,
  academic_year INT NOT NULL,
  quiz_score INT CHECK (quiz_score BETWEEN 0 AND 100),
  typing_score DECIMAL(8, 2) CHECK (typing_score >= 0),
  active_course_score INT CHECK (active_course_score BETWEEN 0 AND 100),
  active_course_modules_completed INT DEFAULT 0,
  active_course_modules_total INT DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, week_number, term, academic_year),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

ALTER TABLE weekly_marks DROP CHECK weekly_marks_typing_score_check;

ALTER TABLE weekly_marks ADD CONSTRAINT weekly_marks_typing_score_check
  CHECK (typing_score >= 0);

CREATE TABLE IF NOT EXISTS competitions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  competition_type VARCHAR(50) DEFAULT 'quiz' CHECK (competition_type IN ('quiz', 'typing', 'maths', 'science', 'stem')),
  eligible_grades JSON DEFAULT ('[]'),
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  practice_available TINYINT(1) DEFAULT FALSE,
  image_url TEXT,
  price_amount DECIMAL(12, 2) DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'KES',
  is_featured TINYINT(1) DEFAULT FALSE,
  is_active TINYINT(1) DEFAULT TRUE,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  CHECK (end_date >= start_date),
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS typing_tests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  term VARCHAR(50),
  academic_year INT,
  week_number INT,
  test_type VARCHAR(50) DEFAULT 'weekly' CHECK (test_type IN ('weekly', 'competition')),
  competition_id INT,
  school_id INT,
  eligible_grades JSON DEFAULT ('[]'),
  eligible_streams JSON DEFAULT ('[]'),
  pass_threshold DECIMAL(8, 2) DEFAULT 25,
  allow_reattempts TINYINT(1) DEFAULT TRUE,
  max_attempts INT DEFAULT 3,
  duration_seconds INT DEFAULT 300,
  deadline_at DATETIME,
  is_published TINYINT(1) DEFAULT FALSE,
  is_open TINYINT(1) DEFAULT FALSE,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE SET NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS typing_lessons (
  id INT AUTO_INCREMENT PRIMARY KEY,
  typing_test_id INT,
  lesson_order INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  passage TEXT NOT NULL,
  instructions TEXT,
  duration_seconds INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(typing_test_id, lesson_order),
  FOREIGN KEY (typing_test_id) REFERENCES typing_tests(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS typing_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  typing_test_id INT,
  typing_lesson_id INT,
  learner_id INT,
  attempt_number INT NOT NULL,
  typed_text TEXT,
  raw_wpm DECIMAL(8, 2) DEFAULT 0,
  accuracy DECIMAL(5, 2) DEFAULT 0,
  mistakes INT DEFAULT 0,
  final_score DECIMAL(8, 2) DEFAULT 0,
  duration_seconds INT,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(typing_lesson_id, learner_id, attempt_number),
  FOREIGN KEY (typing_test_id) REFERENCES typing_tests(id) ON DELETE CASCADE,
  FOREIGN KEY (typing_lesson_id) REFERENCES typing_lessons(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

ALTER TABLE activity_grades
  ADD COLUMN question_marks JSON DEFAULT ('{}');

ALTER TABLE course_allocations ADD COLUMN access_level VARCHAR(20) DEFAULT 'paid';

ALTER TABLE course_allocations DROP CHECK course_allocations_access_level_check;

ALTER TABLE course_allocations ADD CONSTRAINT course_allocations_access_level_check
  CHECK (access_level IN ('preview', 'paid', 'grant', 'scholarship'));

ALTER TABLE course_allocations ADD COLUMN preview_activity_limit INT DEFAULT 0;

ALTER TABLE course_allocations ADD COLUMN paid_at DATETIME;

ALTER TABLE course_allocations ADD COLUMN payment_reference VARCHAR(100);

CREATE TABLE IF NOT EXISTS course_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  course_id INT NOT NULL,
  learner_id INT NOT NULL,
  allocation_id INT,
  provider VARCHAR(50) DEFAULT 'flutterwave',
  tx_ref VARCHAR(100) UNIQUE NOT NULL,
  provider_transaction_id VARCHAR(100),
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(10) NOT NULL DEFAULT 'KES',
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'successful', 'failed')),
  payment_link TEXT,
  raw_response JSON,
  verified_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (allocation_id) REFERENCES course_allocations(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS typing_practice_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  track_key VARCHAR(80) NOT NULL,
  level_number INT NOT NULL CHECK (level_number > 0),
  activity_key VARCHAR(120) NOT NULL,
  activity_title VARCHAR(255) NOT NULL,
  raw_wpm DECIMAL(8, 2) DEFAULT 0,
  net_wpm DECIMAL(8, 2) DEFAULT 0,
  accuracy DECIMAL(5, 2) DEFAULT 0,
  mistakes INT DEFAULT 0,
  duration_seconds INT DEFAULT 0,
  passed TINYINT(1) DEFAULT FALSE,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS quiz_tests (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  description TEXT,
  term VARCHAR(50),
  academic_year INT,
  week_number INT,
  quiz_type VARCHAR(50) DEFAULT 'weekly' CHECK (quiz_type IN ('weekly', 'competition')),
  competition_id INT,
  school_id INT,
  quiz_category VARCHAR(50) DEFAULT 'quiz' CHECK (quiz_category IN ('quiz', 'maths', 'science', 'stem')),
  eligible_grades JSON DEFAULT ('[]'),
  eligible_streams JSON DEFAULT ('[]'),
  pass_score DECIMAL(8, 2) DEFAULT 50,
  max_attempts INT DEFAULT 1,
  duration_seconds INT DEFAULT 600,
  total_points DECIMAL(8, 2) DEFAULT 0 CHECK (total_points >= 0),
  is_published TINYINT(1) DEFAULT FALSE,
  is_open TINYINT(1) DEFAULT FALSE,
  created_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE SET NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS quiz_test_questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quiz_test_id INT,
  position INT NOT NULL DEFAULT 1,
  question_type VARCHAR(50) DEFAULT 'single_choice'
    CONSTRAINT quiz_test_questions_question_type_check
    CHECK (question_type IN ('single_choice', 'multiple_choice', 'true_false', 'short_answer', 'matching', 'ordering')),
  prompt TEXT NOT NULL,
  image_url TEXT,
  options JSON DEFAULT ('[]'),
  correct_answer JSON DEFAULT ('[]'),
  points DECIMAL(8, 2) DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(quiz_test_id, position),
  FOREIGN KEY (quiz_test_id) REFERENCES quiz_tests(id) ON DELETE CASCADE
);

ALTER TABLE quiz_tests
  ADD COLUMN total_points DECIMAL(8, 2) DEFAULT 0;

ALTER TABLE quiz_test_questions
  ADD COLUMN image_url TEXT;

ALTER TABLE quiz_test_questions
  DROP CHECK quiz_test_questions_chk_1;

ALTER TABLE quiz_test_questions
  DROP CHECK quiz_test_questions_question_type_check;

ALTER TABLE quiz_test_questions
  ADD CONSTRAINT quiz_test_questions_question_type_check
  CHECK (question_type IN ('single_choice', 'multiple_choice', 'true_false', 'short_answer', 'matching', 'ordering'));

CREATE TABLE IF NOT EXISTS quiz_test_attempts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  quiz_test_id INT,
  learner_id INT,
  attempt_number INT NOT NULL DEFAULT 1,
  answers JSON DEFAULT ('{}'),
  score DECIMAL(8, 2) DEFAULT 0,
  earned_points DECIMAL(8, 2) DEFAULT 0,
  total_points DECIMAL(8, 2) DEFAULT 0,
  feedback JSON DEFAULT ('{}'),
  duration_seconds INT,
  submitted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(quiz_test_id, learner_id, attempt_number),
  FOREIGN KEY (quiz_test_id) REFERENCES quiz_tests(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_leaderboards (
  id INT AUTO_INCREMENT PRIMARY KEY,
  week_number INT NOT NULL,
  term VARCHAR(50) NOT NULL,
  academic_year INT NOT NULL,
  category VARCHAR(50) NOT NULL CHECK (category IN ('quiz', 'typing', 'active_course')),
  leaderboard_data JSON NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(week_number, term, academic_year, category)
);

CREATE TABLE IF NOT EXISTS certificates (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  course_id INT,
  term VARCHAR(50),
  academic_year INT,
  completion_status VARCHAR(50) DEFAULT 'completed' CHECK (completion_status IN ('completed', 'pending', 'approved', 'issued')),
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'issued')),
  certificate_url TEXT,
  approved_by INT,
  approved_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE,
  FOREIGN KEY (approved_by) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS reports (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  course_id INT,
  report_type VARCHAR(50) NOT NULL,
  term VARCHAR(50),
  academic_year INT,
  data JSON,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS report_feedback (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  school_id INT,
  term VARCHAR(50) NOT NULL,
  academic_year INT NOT NULL,
  comment_text TEXT NOT NULL,
  created_by_user_id INT,
  updated_by_user_id INT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(learner_id, term, academic_year),
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (created_by_user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS audit_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  action VARCHAR(255) NOT NULL,
  entity_type VARCHAR(100),
  entity_id INT,
  old_values JSON,
  new_values JSON,
  ip_address VARCHAR(45),
  user_agent TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS user_consents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  policy_version VARCHAR(50) NOT NULL,
  policy_title VARCHAR(255) NOT NULL,
  consented_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  ip_address VARCHAR(45),
  user_agent TEXT,
  consent_text JSON NOT NULL,
  UNIQUE(user_id, policy_version),
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS learner_parent_consents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_id INT,
  user_id INT,
  parent_full_name VARCHAR(255) NOT NULL,
  parent_phone VARCHAR(50) NOT NULL,
  parent_email VARCHAR(255),
  consent_competition_updates TINYINT(1) DEFAULT FALSE,
  consent_open_course_updates TINYINT(1) DEFAULT FALSE,
  consent_text JSON NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  consented_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS feedback_threads (
  id INT AUTO_INCREMENT PRIMARY KEY,
  learner_user_id INT,
  learner_id INT,
  school_id INT,
  subject VARCHAR(255) DEFAULT 'Learner feedback',
  status VARCHAR(50) DEFAULT 'open' CHECK (status IN ('open', 'closed')),
  learner_last_read_at DATETIME,
  admin_last_read_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (learner_user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE SET NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS feedback_messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  thread_id INT,
  sender_user_id INT,
  sender_role VARCHAR(50) NOT NULL CHECK (sender_role IN ('system_admin', 'learner')),
  message TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (thread_id) REFERENCES feedback_threads(id) ON DELETE CASCADE,
  FOREIGN KEY (sender_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  token_hash VARCHAR(128) UNIQUE NOT NULL,
  requested_by_user_id INT,
  requested_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at DATETIME NOT NULL,
  used_at DATETIME,
  ip_address VARCHAR(45),
  user_agent TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (requested_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS trusted_mfa_devices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  token_hash VARCHAR(128) UNIQUE NOT NULL,
  ip_address VARCHAR(45),
  user_agent TEXT,
  expires_at DATETIME NOT NULL,
  last_used_at DATETIME,
  revoked_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mfa_settings (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNIQUE,
  secret VARCHAR(255),
  backup_codes JSON,
  is_enabled TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS system_settings (
  `key` VARCHAR(100) PRIMARY KEY,
  value JSON NOT NULL,
  updated_by_user_id INT,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

INSERT INTO system_settings (`key`, value)
VALUES (
  'mfa_policy',
  '{"system_admin": true, "school_admin": true}'
)
ON DUPLICATE KEY UPDATE `key` = `key`;

CREATE TABLE IF NOT EXISTS notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  role VARCHAR(50),
  school_id INT,
  title VARCHAR(255) NOT NULL,
  message TEXT NOT NULL,
  notification_type VARCHAR(80) DEFAULT 'info',
  entity_type VARCHAR(100),
  entity_id INT,
  is_read TINYINT(1) DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS template_update_notifications (
  id INT AUTO_INCREMENT PRIMARY KEY,
  template_id INT,
  school_id INT,
  template_version INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(template_id, school_id, template_version),
  FOREIGN KEY (template_id) REFERENCES course_templates(id) ON DELETE CASCADE,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE
);

ALTER TABLE competitions ADD COLUMN image_url TEXT;

ALTER TABLE competitions ADD COLUMN competition_type VARCHAR(50) DEFAULT 'quiz';

ALTER TABLE competitions ADD COLUMN eligible_grades JSON DEFAULT ('[]');

ALTER TABLE competitions DROP CHECK competitions_competition_type_check;

ALTER TABLE competitions ADD CONSTRAINT competitions_competition_type_check
  CHECK (competition_type IN ('quiz', 'typing', 'maths', 'science', 'stem'));

CREATE TABLE IF NOT EXISTS competition_enrollments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  competition_id INT,
  learner_id INT,
  status VARCHAR(50) DEFAULT 'pending_payment' CHECK (status IN ('pending_payment', 'enrolled', 'cancelled')),
  amount_paid DECIMAL(12, 2) DEFAULT 0,
  currency VARCHAR(10) DEFAULT 'KES',
  payment_reference VARCHAR(100),
  enrolled_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(competition_id, learner_id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS competition_payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  competition_id INT,
  learner_id INT,
  enrollment_id INT,
  provider VARCHAR(50) DEFAULT 'flutterwave',
  tx_ref VARCHAR(100) UNIQUE NOT NULL,
  provider_transaction_id VARCHAR(100),
  amount DECIMAL(12, 2) NOT NULL,
  currency VARCHAR(10) DEFAULT 'KES',
  status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'successful', 'failed', 'cancelled')),
  payment_link TEXT,
  raw_response JSON,
  verified_at DATETIME,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE,
  FOREIGN KEY (enrollment_id) REFERENCES competition_enrollments(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS competition_results (
  id INT AUTO_INCREMENT PRIMARY KEY,
  competition_id INT,
  learner_id INT,
  result_stage VARCHAR(50) DEFAULT 'final' CHECK (result_stage IN ('practice', 'final')),
  learner_grade VARCHAR(50),
  competition_type VARCHAR(50) DEFAULT 'quiz',
  quiz_score DECIMAL(6, 2),
  typing_wpm DECIMAL(6, 2),
  typing_accuracy DECIMAL(6, 2),
  total_score DECIMAL(8, 2),
  `rank` INT,
  source VARCHAR(50) DEFAULT 'manual',
  last_synced_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(competition_id, learner_id),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

ALTER TABLE competition_results ADD COLUMN result_stage VARCHAR(50) DEFAULT 'final';

ALTER TABLE competition_results ADD COLUMN learner_grade VARCHAR(50);

ALTER TABLE competition_results ADD COLUMN competition_type VARCHAR(50) DEFAULT 'quiz';

ALTER TABLE competition_results DROP CHECK competition_results_result_stage_check;

ALTER TABLE competition_results ADD CONSTRAINT competition_results_result_stage_check
  CHECK (result_stage IN ('practice', 'final'));

ALTER TABLE competition_results DROP CHECK competition_results_competition_id_learner_id_key;

CREATE UNIQUE INDEX idx_competition_results_unique_stage
  ON competition_results(competition_id, learner_id, result_stage);

CREATE TABLE IF NOT EXISTS competition_reminders (
  id INT AUTO_INCREMENT PRIMARY KEY,
  competition_id INT,
  learner_id INT,
  reminder_type VARCHAR(50) NOT NULL,
  sent_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(competition_id, learner_id, reminder_type),
  FOREIGN KEY (competition_id) REFERENCES competitions(id) ON DELETE CASCADE,
  FOREIGN KEY (learner_id) REFERENCES learners(id) ON DELETE CASCADE
);

CREATE INDEX idx_users_email ON users(email);

CREATE INDEX idx_users_lower_email ON users((LOWER(email)));

CREATE INDEX idx_users_lower_username ON users((LOWER(username)));

CREATE INDEX idx_users_role ON users(role);

CREATE INDEX idx_users_school_id ON users(school_id);

CREATE INDEX idx_users_role_school_active ON users(role, school_id, is_active);

CREATE INDEX idx_learners_user_id ON learners(user_id);

CREATE INDEX idx_schools_code ON schools(code);

CREATE INDEX idx_learners_school_id ON learners(school_id);

CREATE INDEX idx_learners_grade ON learners(grade);

CREATE INDEX idx_learners_term ON learners(term);

CREATE INDEX idx_learners_school_grade_stream_active ON learners(school_id, grade, stream, is_active);

CREATE INDEX idx_learners_lower_email ON learners((LOWER(email)));

CREATE INDEX idx_courses_active_name ON courses(is_active, name);

CREATE INDEX idx_courses_school_template ON courses(school_id, template_id);

CREATE INDEX idx_course_templates_active_name ON course_templates(is_active, name);

CREATE INDEX idx_course_template_modules_template_position ON course_template_modules(template_id, position);

CREATE INDEX idx_course_template_activities_module_position ON course_template_activities(template_module_id, position);

CREATE INDEX idx_course_modules_course_position ON course_modules(course_id, position);

CREATE INDEX idx_learning_activities_module_position ON learning_activities(module_id, position);

CREATE INDEX idx_activity_progress_learner_activity ON activity_progress(learner_id, activity_id);

CREATE INDEX idx_activity_progress_activity_status ON activity_progress(activity_id, status, updated_at);

CREATE INDEX idx_activity_submissions_learner_activity ON activity_submissions(learner_id, activity_id);

CREATE INDEX idx_activity_submissions_activity_status ON activity_submissions(activity_id, status, submitted_at);

CREATE INDEX idx_activity_grades_learner_activity ON activity_grades(learner_id, activity_id);

CREATE INDEX idx_activity_grades_activity_learner ON activity_grades(activity_id, learner_id, graded_at);

CREATE INDEX idx_school_module_schedules_term_week ON school_module_schedules(term_id, week_number);

CREATE INDEX idx_availability_overrides_target ON learning_availability_overrides(course_id, module_id, activity_id, revoked_at);

CREATE INDEX idx_availability_overrides_learner ON learning_availability_overrides(target_learner_id, revoked_at);

CREATE INDEX idx_learner_module_badges_recent ON learner_module_badges(learner_id, updated_at DESC);

CREATE INDEX idx_module_feedback_school_module ON module_feedback(school_id, module_id, updated_at DESC);

CREATE INDEX idx_feedback_identity_audits_feedback ON feedback_identity_audits(feedback_id, created_at DESC);

CREATE INDEX idx_quiz_questions_activity_position ON quiz_questions(activity_id, position);

CREATE INDEX idx_quiz_attempts_learner_activity ON quiz_attempts(learner_id, activity_id);

CREATE INDEX idx_quiz_attempts_activity_learner_attempt ON quiz_attempts(activity_id, learner_id, attempt_number DESC);

CREATE INDEX idx_discussions_activity ON discussions(activity_id);

CREATE INDEX idx_discussion_replies_discussion ON discussion_replies(discussion_id, created_at);

CREATE INDEX idx_course_allocations_learner_id ON course_allocations(learner_id);

CREATE INDEX idx_course_allocations_course_id ON course_allocations(course_id);

CREATE INDEX idx_course_allocations_learner_status ON course_allocations(learner_id, status);

CREATE INDEX idx_course_allocations_course_status ON course_allocations(course_id, status);

CREATE INDEX idx_course_allocations_term_year ON course_allocations(term, academic_year);

CREATE INDEX idx_course_allocations_access_level ON course_allocations(access_level, learner_id, course_id);

CREATE INDEX idx_course_payments_tx_ref ON course_payments(tx_ref);

CREATE INDEX idx_course_payments_provider_transaction ON course_payments(provider_transaction_id);

CREATE INDEX idx_course_payments_allocation ON course_payments(allocation_id);

CREATE INDEX idx_course_payments_status_created ON course_payments(status, created_at);

CREATE INDEX idx_grades_cache_lookup ON grades_cache(learner_id, course_id, term, academic_year);

CREATE INDEX idx_progress_cache_lookup ON progress_cache(learner_id, course_id, term, academic_year);

CREATE INDEX idx_weekly_marks_learner_period ON weekly_marks(learner_id, academic_year, term, week_number);

CREATE INDEX idx_weekly_marks_period ON weekly_marks(academic_year, term, week_number);

CREATE INDEX idx_weekly_leaderboards_period ON weekly_leaderboards(academic_year, term, week_number, category);

CREATE INDEX idx_typing_tests_period ON typing_tests(academic_year, term, week_number, test_type);

CREATE INDEX idx_typing_tests_status ON typing_tests(is_published, is_open, deadline_at);

CREATE INDEX idx_typing_lessons_test_order ON typing_lessons(typing_test_id, lesson_order);

CREATE INDEX idx_typing_attempts_lookup ON typing_attempts(typing_test_id, typing_lesson_id, learner_id, attempt_number);

CREATE INDEX idx_typing_practice_attempts_learner ON typing_practice_attempts(learner_id, submitted_at DESC);

CREATE INDEX idx_typing_practice_attempts_activity ON typing_practice_attempts(learner_id, track_key, level_number, activity_key);

CREATE INDEX idx_quiz_tests_period ON quiz_tests(academic_year, term, week_number, quiz_type);

CREATE INDEX idx_quiz_tests_status ON quiz_tests(is_published, is_open, quiz_type);

CREATE INDEX idx_quiz_tests_competition ON quiz_tests(competition_id, quiz_type);

CREATE INDEX idx_quiz_test_questions_test_position ON quiz_test_questions(quiz_test_id, position);

CREATE INDEX idx_quiz_test_attempts_lookup ON quiz_test_attempts(quiz_test_id, learner_id, attempt_number);

CREATE INDEX idx_certificates_learner_id ON certificates(learner_id);

CREATE INDEX idx_certificates_course_id ON certificates(course_id);

CREATE INDEX idx_certificates_learner_status ON certificates(learner_id, status, completion_status);

CREATE UNIQUE INDEX idx_certificates_unique_award
  ON certificates(learner_id, course_id, (COALESCE(term, '')), (COALESCE(academic_year, '')));

CREATE INDEX idx_reports_learner_id ON reports(learner_id);

CREATE INDEX idx_reports_learner_period_type ON reports(learner_id, academic_year, term, report_type);

CREATE INDEX idx_report_feedback_period ON report_feedback(school_id, academic_year, term);

CREATE INDEX idx_audit_logs_user_id ON audit_logs(user_id);

CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at);

CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);

CREATE INDEX idx_user_consents_user_version ON user_consents(user_id, policy_version);

CREATE INDEX idx_learner_parent_consents_user ON learner_parent_consents(user_id);

CREATE INDEX idx_learner_parent_consents_learner ON learner_parent_consents(learner_id);

CREATE INDEX idx_feedback_threads_learner_user ON feedback_threads(learner_user_id);

CREATE INDEX idx_feedback_threads_school_status_updated ON feedback_threads(school_id, status, updated_at);

CREATE INDEX idx_feedback_threads_updated ON feedback_threads(updated_at);

CREATE INDEX idx_feedback_messages_thread ON feedback_messages(thread_id, created_at);

CREATE INDEX idx_feedback_messages_sender ON feedback_messages(sender_user_id, created_at);

CREATE INDEX idx_password_reset_tokens_hash ON password_reset_tokens(token_hash);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens(user_id);

CREATE INDEX idx_password_reset_tokens_active ON password_reset_tokens(user_id, expires_at) /* predicate dropped: WHERE used_at IS NULL */;

CREATE INDEX idx_trusted_mfa_devices_hash ON trusted_mfa_devices(token_hash);

CREATE INDEX idx_trusted_mfa_devices_user ON trusted_mfa_devices(user_id);

CREATE INDEX idx_trusted_mfa_devices_active ON trusted_mfa_devices(user_id, expires_at) /* predicate dropped: WHERE revoked_at IS NULL */;

CREATE INDEX idx_mfa_settings_user_enabled ON mfa_settings(user_id, is_enabled);

CREATE INDEX idx_system_settings_updated_at ON system_settings(updated_at);

CREATE INDEX idx_notifications_user_id ON notifications(user_id);

CREATE INDEX idx_notifications_role_school ON notifications(role, school_id);

CREATE INDEX idx_notifications_created_at ON notifications(created_at);

CREATE INDEX idx_notifications_unread_user ON notifications(user_id, is_read, created_at);

CREATE INDEX idx_template_update_notifications_school
  ON template_update_notifications(school_id, template_id, template_version);

CREATE INDEX idx_competitions_dates ON competitions(start_date, end_date);

CREATE INDEX idx_competitions_featured ON competitions(is_featured, is_active);

CREATE INDEX idx_competitions_active_dates ON competitions(is_active, start_date, end_date);

CREATE INDEX idx_competitions_type ON competitions(competition_type);

-- dropped idx_competitions_eligible_grades: GIN index, unused (eligible_grades is filtered in application code);

CREATE INDEX idx_courses_category_active ON courses(course_category, is_active);

CREATE INDEX idx_competition_enrollments_competition ON competition_enrollments(competition_id);

CREATE INDEX idx_competition_enrollments_learner ON competition_enrollments(learner_id);

CREATE INDEX idx_competition_enrollments_learner_status ON competition_enrollments(learner_id, status, updated_at);

CREATE INDEX idx_competition_enrollments_competition_status ON competition_enrollments(competition_id, status);

CREATE INDEX idx_competition_payments_tx_ref ON competition_payments(tx_ref);

CREATE INDEX idx_competition_payments_provider_transaction ON competition_payments(provider_transaction_id);

CREATE INDEX idx_competition_payments_status_created ON competition_payments(status, created_at);

CREATE INDEX idx_competition_payments_enrollment ON competition_payments(enrollment_id);

CREATE INDEX idx_competition_results_competition ON competition_results(competition_id, total_score);

CREATE INDEX idx_competition_results_rank ON competition_results(competition_id, `rank`);

CREATE INDEX idx_competition_results_learner ON competition_results(learner_id);

CREATE INDEX idx_competition_results_filters ON competition_results(competition_id, result_stage, learner_grade, competition_type, total_score);

CREATE INDEX idx_competition_reminders_competition ON competition_reminders(competition_id);

CREATE INDEX idx_competition_reminders_learner ON competition_reminders(learner_id, sent_at);

UPDATE learners l
  JOIN users u
  SET user_id = u.id
  WHERE l.user_id IS NULL
  AND u.role = 'learner'
  AND u.school_id = l.school_id
  AND u.full_name = l.full_name;

CREATE TABLE IF NOT EXISTS ai_settings (
  id INT PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  is_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  enabled_roles JSON NOT NULL DEFAULT ('{}'),
  default_provider_key VARCHAR(50),
  fallback_provider_key VARCHAR(50),
  max_requests_per_hour INT NOT NULL DEFAULT 50,
  max_tokens_per_hour INT NOT NULL DEFAULT 100000,
  max_requests_per_day INT NOT NULL DEFAULT 250,
  max_tokens_per_day INT NOT NULL DEFAULT 500000,
  retain_prompt_days INT NOT NULL DEFAULT 0,
  debug_logging_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  updated_by_user_id INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ai_providers (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provider_key VARCHAR(50) UNIQUE NOT NULL,
  display_name VARCHAR(120) NOT NULL,
  base_url TEXT,
  api_key_ciphertext TEXT,
  default_model VARCHAR(120),
  fallback_model VARCHAR(120),
  is_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  is_default TINYINT(1) NOT NULL DEFAULT FALSE,
  config JSON NOT NULL DEFAULT ('{}'),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_role_limits (
  role VARCHAR(30) PRIMARY KEY,
  is_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  requests_per_hour INT NOT NULL DEFAULT 10,
  tokens_per_hour INT NOT NULL DEFAULT 20000,
  requests_per_day INT NOT NULL DEFAULT 40,
  tokens_per_day INT NOT NULL DEFAULT 80000,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS school_ai_settings (
  school_id INT PRIMARY KEY,
  is_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  school_admin_enabled TINYINT(1) NOT NULL DEFAULT TRUE,
  teacher_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  learner_enabled TINYINT(1) NOT NULL DEFAULT FALSE,
  notes TEXT,
  updated_by_user_id INT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE,
  FOREIGN KEY (updated_by_user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ai_usage_logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT,
  school_id INT,
  role VARCHAR(30),
  provider_key VARCHAR(50),
  model VARCHAR(120),
  feature VARCHAR(80),
  activity_id INT,
  prompt_tokens INT NOT NULL DEFAULT 0,
  completion_tokens INT NOT NULL DEFAULT 0,
  total_tokens INT NOT NULL DEFAULT 0,
  estimated_cost DECIMAL(12, 6) NOT NULL DEFAULT 0,
  status VARCHAR(30) NOT NULL DEFAULT 'pending',
  error_message TEXT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL
);

CREATE INDEX idx_ai_usage_logs_user_created ON ai_usage_logs(user_id, created_at);

CREATE INDEX idx_ai_usage_logs_school_created ON ai_usage_logs(school_id, created_at);

CREATE INDEX idx_ai_usage_logs_role_created ON ai_usage_logs(role, created_at);

CREATE INDEX idx_ai_usage_logs_feature_created ON ai_usage_logs(feature, created_at);

CREATE INDEX idx_school_ai_settings_updated ON school_ai_settings(updated_at);

-- ---------------------------------------------------------------------------
-- Folded in from migrations 002, 003 and 004. Those ran through the PostgreSQL
-- migration runner, which has no part in the MySQL setup, so anything they
-- created has to live here or it simply never exists.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS user_sessions (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  refresh_token_hash VARCHAR(64) NOT NULL UNIQUE,
  token_family_id CHAR(36) NOT NULL,
  device_name VARCHAR(255),
  ip_address VARCHAR(45),
  user_agent TEXT,
  last_used_at DATETIME,
  expires_at DATETIME NOT NULL,
  revoked_at DATETIME,
  revoke_reason VARCHAR(255),
  replaced_by_session_id BIGINT REFERENCES user_sessions(id) ON DELETE SET NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_sessions_user_active ON user_sessions(user_id, expires_at);

CREATE INDEX idx_user_sessions_family ON user_sessions(token_family_id, created_at);

CREATE INDEX idx_user_sessions_expiry ON user_sessions(expires_at);

ALTER TABLE users ADD COLUMN mfa_code_hash VARCHAR(64);

ALTER TABLE users ADD COLUMN mfa_code_attempts INT NOT NULL DEFAULT 0;

ALTER TABLE users ADD COLUMN mfa_code_created_at DATETIME;

CREATE INDEX idx_school_admins_school ON school_admins(school_id);

CREATE INDEX idx_courses_template ON courses(template_id);

CREATE INDEX idx_course_modules_template_module ON course_modules(template_module_id);

CREATE INDEX idx_learning_activities_template_activity ON learning_activities(template_activity_id);

CREATE INDEX idx_activity_grades_submission ON activity_grades(submission_id);

CREATE INDEX idx_availability_overrides_school_module ON learning_availability_overrides(school_id, module_id);

CREATE INDEX idx_availability_overrides_activity ON learning_availability_overrides(activity_id);

CREATE INDEX idx_learner_badges_course_module ON learner_module_badges(course_id, module_id);

CREATE INDEX idx_module_feedback_course_module ON module_feedback(course_id, module_id);

CREATE INDEX idx_discussions_created_by ON discussions(created_by_user_id);

CREATE INDEX idx_discussion_replies_learner ON discussion_replies(learner_id);

CREATE INDEX idx_discussion_replies_parent ON discussion_replies(parent_reply_id);

CREATE INDEX idx_grades_cache_course ON grades_cache(course_id);

CREATE INDEX idx_progress_cache_course ON progress_cache(course_id);

CREATE INDEX idx_typing_tests_school_competition ON typing_tests(school_id, competition_id);

CREATE INDEX idx_typing_attempts_learner ON typing_attempts(learner_id);

CREATE INDEX idx_course_payments_learner_course ON course_payments(learner_id, course_id);

CREATE INDEX idx_quiz_tests_school ON quiz_tests(school_id);

CREATE INDEX idx_quiz_test_attempts_learner ON quiz_test_attempts(learner_id);

CREATE INDEX idx_reports_course ON reports(course_id);

CREATE INDEX idx_feedback_threads_learner ON feedback_threads(learner_id);

CREATE INDEX idx_notifications_school_created ON notifications(school_id, created_at DESC);

CREATE INDEX idx_competition_payments_learner_competition ON competition_payments(learner_id, competition_id);

CREATE INDEX idx_user_sessions_replacement ON user_sessions(replaced_by_session_id);

SET FOREIGN_KEY_CHECKS = 1;
