const q = (prompt, options, answer, reason) => ({
  prompt,
  options,
  answer,
  reason,
  hint: `Think about what the project must do immediately before or after "${answer}".`,
  explanation: `${answer} is correct because ${reason}`,
});

const module1RichHtml = require("./scratchExplorer.module1RichHtml");
const module4RichHtml = require("./scratchExplorer.module4RichHtml");

module.exports = [
  {
    title: "Module 1 - Welcome to Creative Coding",
    focus: "events, sequences, sprites, the Stage, and safe project saving",
    outcome: "a welcoming animation that follows a clear sequence and can be safely saved and reopened",
    introduction: "Coding is a way to communicate an idea through precise instructions. In this first mission, you will learn how Educlub activities work, how Scratch sprites respond to events, and how to save evidence without sharing private information.",
    concepts: [["event", "starts a script when something happens"], ["sequence", "places instructions in the order they must run"], ["sprite", "is a programmable character or object"], ["Stage", "is the area where the project is performed"]],
    algorithm: ["Choose a sprite and backdrop.", "Start when the green flag is clicked.", "Move the sprite to a clear starting position.", "Show a greeting with movement, sound, or a costume change.", "Finish in a planned pose.", "Save, reopen, and test the .sb3 project."],
    steam: "digital communication, animation, and precise instructional language",
    predict: "If two motion blocks exchange places, how will the final position or movement change?",
    misconception: "Scratch blocks do not run merely because they are visible; a script needs an event or another script to start it.",
    debugging: "Check that every stack is connected beneath the intended event and that the sprite begins from a known position.",
    support: "Use one sprite, one event, and four blocks before adding sound or costumes.",
    discussion: {
      prompt: "A computer follows instructions exactly, while a person often guesses missing details. Discuss why precise instructions matter in coding and in everyday activities.",
      questions: ["Which everyday instruction could be misunderstood?", "How can we make a sequence easier to follow?", "What information should never be placed in a public project?"],
    },
    practice: {
      title: "Make a Character Come Alive",
      brief: "Animate one sprite so it starts in a planned place, greets the viewer, moves, changes appearance, and finishes clearly.",
      steps: ["Add a green-flag event and set the starting x and y position.", "Add a greeting, a short movement, and a costume or size change.", "Use waits so the viewer can follow the sequence."],
      checks: ["the green flag always starts the animation", "the sprite starts in the same place", "the actions happen in an understandable order"],
    },
    projects: [
      { title: "My Name in Motion", brief: "Create an animated title using letters, shapes, or invented symbols that move and change in a planned sequence without revealing a full private name.", features: ["at least three animated symbols", "a clear beginning and ending", "two different kinds of animation", "safe non-private text"] },
      { title: "Educlub Welcome Card", brief: "Design an interactive welcome card for a new learner that explains one helpful learning habit through animation, sound, and friendly instructions.", features: ["a useful welcome message", "one animated character", "one learner action", "a clear saving or testing tip"] },
    ],
    challenge: { title: "Clickable Surprise", brief: "Add an optional sprite that reveals a safe encouraging message only when the learner clicks it.", steps: ["Choose a visual clue that suggests clicking.", "Use a clicked-sprite event.", "Reveal and then reset the message."], checks: ["the surprise does not start automatically", "the message is kind and safe", "the main animation still works"] },
    quiz: [
      q("Which block category contains the green-flag event?", ["Events", "Motion", "Sound", "Looks"], "Events", "events start scripts when something happens."),
      q("What is a sequence?", ["instructions in order", "a sprite picture", "a saved password", "a random sound"], "instructions in order", "Scratch runs connected blocks from top to bottom."),
      q("Why set a starting position?", ["to make tests repeatable", "to rename Scratch", "to hide all blocks", "to publish automatically"], "to make tests repeatable", "the same test should begin from the same state."),
      q("Which file should be uploaded for a Scratch project?", [".sb3", ".exe", ".password", ".html only"], ".sb3", "Scratch saves editable projects in the .sb3 format."),
      q("Which text is safest in a project?", ["CoderStar welcome", "my home address", "my password", "my phone number"], "CoderStar welcome", "a nickname avoids revealing private identifying information."),
    ],
    rich_html: module1RichHtml,
  },
  {
    title: "Module 2 - Story Studio",
    focus: "backdrops, costumes, dialogue timing, storyboards, and broadcast messages",
    outcome: "a three-scene story in which characters speak in order and scenes change reliably",
    introduction: "Interactive stories combine writing, performance, visual design, and code. You will storyboard before coding so each scene has a purpose and every character knows when to act.",
    concepts: [["storyboard", "plans scenes before animation begins"], ["backdrop", "shows the setting on the Stage"], ["costume", "changes a sprite's pose or appearance"], ["broadcast", "sends a message that other sprites can receive"]],
    algorithm: ["Show the title scene.", "Introduce the setting and characters.", "Play dialogue in the planned order.", "Broadcast a message to begin scene two.", "Change backdrops and character actions.", "Broadcast the final scene and show a clear ending."],
    steam: "language, drama, visual art, sequencing, and audience design",
    predict: "What happens if both characters speak at the same time and no wait or broadcast controls the order?",
    misconception: "Long guessed wait blocks are less reliable than broadcasts that name exactly when the next scene should start.",
    debugging: "Check which sprite sends each message, which scripts receive it, and whether dialogue has enough time to be read.",
    support: "Use supplied scene headings and two characters with one line each before expanding the story.",
    discussion: {
      prompt: "Stories can teach, entertain, or persuade. Discuss how an interactive story changes when the viewer can influence what a character does.",
      questions: ["What should the viewer understand in scene one?", "How can dialogue remain kind and believable?", "When is a broadcast better than a long wait?"],
    },
    practice: {
      title: "Two-Character Conversation",
      brief: "Create a short conversation where two sprites greet one another, respond in order, and use a broadcast to finish the exchange.",
      steps: ["Write four short lines before coding.", "Use say-for-seconds and waits or broadcast-and-wait.", "Send a final message that changes a pose or backdrop."],
      checks: ["speech does not overlap", "both sprites take part", "a broadcast controls an important change"],
    },
    projects: [
      { title: "A Helpful Choice", brief: "Create a three-scene story where a character faces a school, friendship, environmental, or community choice and learns from the result.", features: ["three planned scenes", "two speaking characters", "a meaningful problem and response", "an ending that explains the lesson"] },
      { title: "Journey to an Imagined World", brief: "Create an original adventure through three contrasting settings, using broadcasts and costumes to coordinate travel and character reactions.", features: ["three distinct backdrops", "coordinated scene broadcasts", "costumes show changing reactions", "a clear return or final destination"] },
    ],
    challenge: { title: "Viewer Choice", brief: "Let the viewer choose between two safe actions and send the story to two different endings.", steps: ["Ask a short choice question.", "Check both accepted answers.", "Broadcast the matching ending."], checks: ["both choices work", "unexpected input receives guidance", "the story can restart"] },
    quiz: [
      q("What plans a story before coding?", ["storyboard", "variable", "clone", "timer"], "storyboard", "a storyboard records scenes, actions, and dialogue."),
      q("What changes the Stage setting?", ["backdrop", "sprite size", "answer", "pen color"], "backdrop", "backdrops provide different scene settings."),
      q("Which tool coordinates a scene change?", ["broadcast", "mouse x", "volume", "username"], "broadcast", "named messages can start scripts on several sprites."),
      q("Why avoid overlapping dialogue?", ["the audience needs to follow it", "it makes files smaller", "it changes coordinates", "it creates variables"], "the audience needs to follow it", "readable timing supports communication."),
      q("What should every story ending do?", ["resolve or clearly close the action", "start every script again", "hide the project title", "delete the characters"], "resolve or clearly close the action", "the audience needs a planned conclusion."),
    ],
  },
  {
    title: "Module 3 - Animation and Music Lab",
    focus: "costume animation, sound, tempo, parallel scripts, and synchronization",
    outcome: "a short performance in which movement, costumes, sound, and scene changes work together",
    introduction: "Animators and musicians both organize change over time. Scratch lets separate scripts perform together, but good synchronization requires planned cues and repeated testing.",
    concepts: [["tempo", "describes how fast a musical beat moves"], ["animation", "creates the appearance of movement by changing images"], ["parallel", "describes scripts running at the same time"], ["cue", "signals when a performer or script should act"]],
    algorithm: ["Choose a short sound or rhythm.", "Set each performer at a starting position.", "Begin sound and movement together.", "Change costumes in a repeating rhythm.", "Broadcast a cue for the next scene.", "Finish performers and sound together."],
    steam: "music, rhythm, performance, costume art, and animation timing",
    predict: "If one performer waits 0.5 seconds and another waits 1 second, when will their movements stop matching?",
    misconception: "Scripts that begin together do not automatically remain synchronized when their waits and loop lengths differ.",
    debugging: "Use short sections and shared broadcast cues to find exactly where sound and movement drift apart.",
    support: "Animate one performer to four beats before adding another sprite or scene.",
    discussion: {
      prompt: "A performance can represent many cultures and styles. Discuss how to create respectfully without copying stereotypes or claiming another person's work.",
      questions: ["How can rhythm be represented with blocks?", "What makes a performance respectful?", "Which cue should all performers share?"],
    },
    practice: {
      title: "Four-Beat Dance",
      brief: "Animate one sprite through a repeating four-beat movement using costume changes, waits, and a short sound.",
      steps: ["Choose four simple poses or movements.", "Use equal waits to create a steady beat.", "Repeat the phrase and finish in the starting pose."],
      checks: ["four beats are visible", "costumes or movement create animation", "the phrase repeats consistently"],
    },
    projects: [
      { title: "Digital Music Performance", brief: "Create a short original performance with at least two performers, a title scene, synchronized movement, and a planned finale.", features: ["two coordinated performers", "intentional sound or notes", "a title and final scene", "broadcast cues maintain timing"] },
      { title: "Animated Celebration", brief: "Design a respectful celebration of a safe personal, school, fictional, or community theme using original visuals, rhythm, and scene transitions.", features: ["theme is explained", "animation supports the theme", "sound is credited or original", "transitions are synchronized"] },
    ],
    challenge: { title: "Remix Controls", brief: "Add controls that let the viewer change the tempo, performer, or visual effect without breaking the performance.", steps: ["Choose one safe control key or button.", "Change one performance variable.", "Test minimum and maximum values."], checks: ["control instructions are visible", "changes are bounded", "the performance can reset"] },
    quiz: [
      q("What is tempo?", ["speed of a beat", "sprite position", "project name", "image description"], "speed of a beat", "tempo controls how quickly musical beats occur."),
      q("What creates animation?", ["changing images over time", "one still costume", "deleting sounds", "hiding scripts"], "changing images over time", "the eye interprets changing poses as motion."),
      q("What are parallel scripts?", ["scripts running together", "two file names", "matching questions", "hidden comments"], "scripts running together", "Scratch can execute more than one stack at once."),
      q("What helps performers resynchronize?", ["shared broadcast cue", "random wait", "larger sprite", "new username"], "shared broadcast cue", "all receiving scripts react to the same named event."),
      q("Why test a performance in short sections?", ["to locate timing drift", "to remove all sound", "to change the Stage size", "to avoid saving"], "to locate timing drift", "small tests identify the first place behavior differs."),
    ],
  },
  {
    title: "Module 4 - Shapes, Patterns and Digital Art",
    focus: "coordinates, direction, repeat loops, angles, pen drawing, and symmetry",
    outcome: "a digital art project that constructs accurate shapes and transforms them into an intentional pattern",
    introduction: "Artists and mathematicians both explore shape, repetition, balance, and change. You will use pen movement as a visible record of an algorithm.",
    concepts: [["coordinate", "locates a point with x and y values"], ["angle", "measures an amount of turn"], ["loop", "repeats instructions"], ["symmetry", "describes balanced matching parts"]],
    algorithm: ["Clear earlier pen marks.", "Move to a planned starting coordinate.", "Put the pen down.", "Repeat move and turn to draw one shape.", "Change color, position, size, or turn.", "Repeat the shape to create a larger pattern."],
    steam: "geometry, visual art, textiles, architecture, and pattern recognition",
    predict: "What regular shape will appear when a sprite repeats move and turn 90 degrees four times?",
    misconception: "The outside turn for a regular shape is 360 divided by the number of sides, not the inside angle shown in some geometry diagrams.",
    debugging: "Count loop repetitions and verify that the total turning returns the sprite to its original direction.",
    support: "Use a square loop first, display direction, and trace each turn with a finger.",
    discussion: {
      prompt: "Patterns appear in art, buildings, clothing, plants, and technology. Discuss how repetition can create unity while small changes create interest.",
      questions: ["Where have you noticed symmetry?", "How does a loop help an artist?", "When does a repeated pattern become too crowded?"],
    },
    practice: {
      title: "Shape Drawing Machine",
      brief: "Use the pen extension and a repeat loop to draw a square, triangle, and hexagon from known side and turn values.",
      steps: ["Add the pen extension and clear the Stage.", "Draw a square with repeat four and 90-degree turns.", "Change repetitions and turn to make two more shapes."],
      checks: ["each shape closes", "the correct loop count is used", "the Stage clears before a new test"],
    },
    projects: [
      { title: "Pattern and Mandala Studio", brief: "Create an original radial or tiled pattern by repeating a shape while changing turn, color, size, or position in a controlled way.", features: ["one accurate base shape", "a larger repeated pattern", "planned color choices", "the algorithm can redraw the art"] },
      { title: "Digital Textile or Tile", brief: "Design a repeating motif inspired by nature, geometry, or an original symbol, and explain how translation, rotation, or reflection builds the design.", features: ["an original motif", "visible transformation", "balanced spacing", "a written mathematical explanation"] },
    ],
    challenge: { title: "User-Controlled Art", brief: "Ask the viewer for sides, size, or color and redraw a valid pattern from the chosen value.", steps: ["Ask for one numeric value.", "Check that it is inside a safe range.", "Use it in the drawing algorithm."], checks: ["valid input changes the art", "invalid input receives guidance", "repeated drawings can be cleared"] },
    quiz: [
      q("Which pair locates a sprite?", ["x and y", "sound and tempo", "costume and size", "answer and timer"], "x and y", "coordinates use horizontal and vertical values."),
      q("How many 90-degree outside turns close a square?", ["4", "3", "5", "8"], "4", "four equal sides and turns return to the start."),
      q("What does a loop do?", ["repeats instructions", "saves a password", "changes the editor", "uploads a file"], "repeats instructions", "loops avoid copying the same blocks many times."),
      q("What should happen before a fresh drawing test?", ["clear pen marks", "delete Scratch", "hide all sprites", "change the computer clock"], "clear pen marks", "old marks would make results difficult to compare."),
      q("What is symmetry?", ["balanced matching parts", "a random score", "a spoken answer", "one keyboard key"], "balanced matching parts", "symmetry describes correspondence across a line or around a point."),
    ],
    rich_html: module4RichHtml,
  },
  {
    title: "Module 5 - Maze Mission",
    focus: "keyboard input, sensing, conditions, collision correction, and coordinates",
    outcome: "a controllable maze or rover challenge with dependable walls, a goal, instructions, and restart behavior",
    introduction: "Navigation systems repeatedly sense a situation, make a decision, and correct movement. Your maze player or rover will use the same input-rule-output cycle.",
    concepts: [["input", "is information given to a program"], ["condition", "asks a yes-or-no question"], ["sensing", "checks contact, distance, color, or another changing fact"], ["collision", "occurs when game objects touch"]],
    algorithm: ["Set the player at the start.", "Read one direction key.", "Move a small distance.", "Check for wall contact.", "Undo invalid movement.", "Check for the goal and show success or continue."],
    steam: "robot navigation, maps, coordinates, spatial reasoning, and resilient design",
    predict: "Why might moving 30 steps at once allow a sprite to cross a thin wall without noticing it?",
    misconception: "A collision check after a very large movement can miss a wall because the sprite jumps from one side to the other.",
    debugging: "Use small movement steps, show the start coordinates, and test every wall direction and restart path.",
    support: "Begin with one horizontal corridor and two direction keys before using a full maze.",
    discussion: {
      prompt: "A rover cannot ask a driver to move every wheel directly. Discuss what information a rover needs to navigate safely in an unfamiliar place.",
      questions: ["Which inputs could guide a rover?", "Why should movement be tested in small steps?", "What should happen after an obstacle is detected?"],
    },
    practice: {
      title: "Wall-Safe Movement",
      brief: "Control a sprite with arrow keys and make contact with a colored wall undo the most recent movement.",
      steps: ["Set a known start position.", "Create small movements for four arrow keys.", "After each movement, check wall color and move back if touching."],
      checks: ["all four keys move correctly", "the sprite cannot remain inside a wall", "restart returns to the exact start"],
    },
    projects: [
      { title: "Moon Rover Rescue", brief: "Guide a rover through a lunar map to collect a supply and reach a safe landing site while avoiding craters or restricted areas.", features: ["clear mission instructions", "collision-safe navigation", "one collectible or checkpoint", "goal and restart feedback"] },
      { title: "Community Maze", brief: "Create a maze where a character safely travels between useful fictional community locations and learns one navigation or safety message.", features: ["readable map and labels", "dependable walls", "a meaningful destination", "kind useful feedback"] },
    ],
    challenge: { title: "Timer, Hazard or Second Level", brief: "Add one advanced game system that increases challenge while remaining fair and clearly explained.", steps: ["Choose timer, moving hazard, or second level.", "Define the new rule before coding.", "Test that the player can still succeed."], checks: ["new rule is explained", "difficulty remains fair", "restart resets the added system"] },
    quiz: [
      q("What should happen after a small maze movement?", ["check wall contact", "delete the Stage", "stop all scripts forever", "change the project name"], "check wall contact", "collision must be detected immediately after movement."),
      q("Which block chooses an action from a yes-or-no test?", ["if", "say", "play sound", "set size"], "if", "an if block runs code only when its condition is true."),
      q("Why use small movement steps?", ["to detect thin walls reliably", "to remove controls", "to hide coordinates", "to erase the map"], "to detect thin walls reliably", "the sprite is less likely to jump past an obstacle."),
      q("What should restart reset?", ["position and game state", "only the sprite name", "the Scratch language", "the browser history"], "position and game state", "a new attempt needs the same starting conditions."),
      q("What makes a maze fair?", ["clear controls and possible routes", "invisible rules", "unreachable goals", "randomly changing controls"], "clear controls and possible routes", "the player must understand and be able to satisfy the rules."),
    ],
  },
  {
    title: "Module 6 - Catch, Score and Improve",
    focus: "variables, random positions, loops, scoring rules, timers, and feedback",
    outcome: "a timed collection game with clear rules, fair scoring, useful feedback, and a dependable ending",
    introduction: "Games use variables to remember what has happened. You will design a score system that rewards the intended action and helps the player understand every change.",
    concepts: [["variable", "stores information that can change"], ["random", "selects an unpredictable value inside a range"], ["score", "records progress according to game rules"], ["timer", "measures elapsed time"]],
    algorithm: ["Reset score and game time.", "Place or spawn an object.", "Move it or wait for a player action.", "Check for a catch or miss.", "Update score and feedback.", "Repeat until time ends, then show the result."],
    steam: "classification, probability, environmental choices, health, and arithmetic",
    predict: "What unfair result occurs when a score variable is not reset before a new round?",
    misconception: "Random does not mean without rules; useful random ranges must keep objects visible and reachable.",
    debugging: "Show the score and timer, test both catch and miss paths, and confirm a new round resets every changing value.",
    support: "Use click-to-catch objects before attempting falling movement or multiple object types.",
    discussion: {
      prompt: "Points influence player behavior. Discuss how a scoring rule can encourage useful decisions or accidentally reward the wrong action.",
      questions: ["What action deserves a point?", "When should points be removed?", "How can random spawning remain fair?"],
    },
    practice: {
      title: "Random Collectible",
      brief: "Make one object move to a reachable random position when clicked, increase score, and give immediate visual or sound feedback.",
      steps: ["Create and display a score variable.", "Reset score at the green flag.", "On click, change score and go to a random visible position."],
      checks: ["score begins at zero", "every valid catch changes score once", "the object remains reachable"],
    },
    projects: [
      { title: "Clean-Ocean Collector", brief: "Create a timed game that rewards collecting litter while protecting sea life, with clear visual differences and constructive feedback.", features: ["litter and sea life are distinguishable", "score rewards the intended choice", "timer ends the round", "final message explains the result"] },
      { title: "Healthy Choice Catch", brief: "Create a game that asks the player to collect items that match a chosen balanced-meal, exercise, or wellbeing rule without judging people.", features: ["rule is factual and respectful", "correct and incorrect objects behave differently", "score and timer reset", "feedback teaches the chosen rule"] },
    ],
    challenge: { title: "Bonus and Penalty Objects", brief: "Add two object types with different values, spawn rates, and visible clues so the player can make a fair decision.", steps: ["Define each point value.", "Choose fair random timing.", "Test ten spawns and adjust balance."], checks: ["objects are visibly different", "point changes match the rules", "rare objects do not make success impossible"] },
    quiz: [
      q("What stores a changing score?", ["variable", "costume", "backdrop", "comment"], "variable", "variables hold values that scripts can read and change."),
      q("When should score reset?", ["at the start of a round", "after every point", "only after saving", "never"], "at the start of a round", "each attempt should begin under the same rule."),
      q("What makes a random position fair?", ["it stays visible and reachable", "it is always outside the Stage", "it never changes", "it hides the object"], "it stays visible and reachable", "the player must have a reasonable chance to act."),
      q("What does a timer measure?", ["elapsed time", "sprite color", "file size", "answer text"], "elapsed time", "Scratch's timer reports seconds since it was reset."),
      q("Why give feedback after a catch?", ["to explain the result of the action", "to hide the score", "to stop saving", "to rename variables"], "to explain the result of the action", "players learn the rule from immediate response."),
    ],
  },
  {
    title: "Module 7 - Quiz Maker",
    focus: "ask-and-answer input, conditions, operators, score, validation, and explanatory feedback",
    outcome: "a five-question quiz that checks answers fairly, teaches through feedback, and reports a meaningful result",
    introduction: "A good quiz is more than a score. It asks clear questions, accepts reasonable answers, explains mistakes, and helps the learner decide what to practise.",
    concepts: [["answer", "stores the latest response entered after an ask block"], ["operator", "compares, calculates, or joins values"], ["validation", "checks whether input follows an expected rule"], ["feedback", "explains what happened and how to improve"]],
    algorithm: ["Reset score.", "Ask a clear question.", "Read and normalize the answer.", "Compare it with the accepted answer.", "Give specific feedback and update score.", "Repeat for five questions and report the result."],
    steam: "assessment design, language, mathematics, science communication, and fairness",
    predict: "What happens if a second ask block runs before the first answer has been checked?",
    misconception: "The answer reporter contains only the most recent response, so each answer must be checked before asking the next question.",
    debugging: "Test correct, incorrect, uppercase, lowercase, blank, and unexpected answers, then inspect score after each test.",
    support: "Build and fully test one question before copying its structure for the remaining questions.",
    discussion: {
      prompt: "A question can be factually correct yet confusing or unfair. Discuss what makes a quiz question clear, respectful, and useful for learning.",
      questions: ["What makes wording unambiguous?", "How should incorrect answers be treated?", "When should more than one answer be accepted?"],
    },
    practice: {
      title: "One Question with Teaching Feedback",
      brief: "Build one question that checks the response, changes score only when appropriate, and explains why the correct answer works.",
      steps: ["Write one question and accepted answer.", "Ask and compare the answer.", "Create different correct and incorrect feedback."],
      checks: ["correct answer receives a point", "incorrect answer does not receive a point", "both paths receive useful feedback"],
    },
    projects: [
      { title: "STEM Knowledge Challenge", brief: "Create a five-question quiz about a science, technology, engineering, or maths topic you can verify from reliable class materials.", features: ["five verified questions", "clear accepted answers", "specific explanations", "a final score with next-step advice"] },
      { title: "School or Hobby Quiz Show", brief: "Create a welcoming quiz about a safe school subject, book, sport, music, art, or hobby without requiring private knowledge.", features: ["questions suit the intended audience", "answer checking is consistent", "feedback remains kind", "instructions and final result are clear"] },
    ],
    challenge: { title: "Countdown or Question Bank", brief: "Add either a fair visible countdown or a list-based question bank after the required quiz is reliable.", steps: ["Choose one extension and define its rule.", "Build it without changing correct scoring.", "Test all five questions again."], checks: ["core scoring still works", "extension is explained", "the quiz can restart cleanly"] },
    quiz: [
      q("Where is typed quiz input stored?", ["answer", "mouse y", "costume number", "volume"], "answer", "the answer reporter changes after each ask block."),
      q("What does validation do?", ["checks input against a rule", "draws a sprite", "records sound", "changes the Stage size"], "checks input against a rule", "validation decides whether data is acceptable."),
      q("When should score increase?", ["after a correct response", "before every question", "after every response", "when saving"], "after a correct response", "score must follow the stated rule."),
      q("What is useful incorrect feedback?", ["an explanation and next step", "a rude message", "silence", "a random animation only"], "an explanation and next step", "feedback should help the learner improve."),
      q("Why test blank input?", ["users may submit nothing", "it changes costumes", "it saves the file", "it starts the timer"], "users may submit nothing", "validation should handle realistic unexpected input."),
    ],
  },
  {
    title: "Module 8 - Nature in Motion",
    focus: "multiple sprites, direction, repeated rules, broadcasts, distance sensing, and simple models",
    outcome: "an animation or model showing how animals move, migrate, or coordinate without constant collisions",
    introduction: "Scientists use models to explore movement that is difficult to observe all at once. You will create simple rules and then watch how group behavior emerges.",
    concepts: [["model", "is a simplified representation used to explore an idea"], ["migration", "is regular movement from one region to another"], ["distance", "measures separation between objects"], ["coordination", "organizes actions so a group can work together"]],
    algorithm: ["Create the animals and destination.", "Give each animal a starting position and direction.", "Move repeatedly toward a target or route.", "Check distance from neighbors or obstacles.", "Turn, slow, or spread out when too close.", "Reach the destination and report what happened."],
    steam: "biology, animal adaptation, geography, movement, and scientific modelling",
    predict: "What pattern might appear if every animal follows the same rule to turn away when another animal is very close?",
    misconception: "A model does not prove that real animals use exactly the same rule; it helps investigate whether a rule could produce a pattern.",
    debugging: "Slow the movement, show distance values, and test with two sprites before increasing the group.",
    support: "Animate one animal following a route, then duplicate it only after the route works.",
    discussion: {
      prompt: "Large groups of animals can move without a leader giving every instruction. Discuss how simple local rules might create organized group movement.",
      questions: ["What information can one animal sense nearby?", "Why do animals migrate?", "What limitation does our Scratch model have?"],
    },
    practice: {
      title: "Follow a Migration Route",
      brief: "Animate one bird, fish, or fictional creature following a route between seasonal locations and explain the reason for movement.",
      steps: ["Mark a start, route point, and destination.", "Use direction and movement blocks.", "Add one message explaining the environmental reason."],
      checks: ["the route is visible", "movement reaches the destination", "the explanation connects movement to a need"],
    },
    projects: [
      { title: "Moving Together", brief: "Model a group that moves toward a destination while turning or slowing when members become too close to one another.", features: ["at least three moving members", "a shared destination", "a distance-based spacing rule", "observations about the resulting pattern"] },
      { title: "Long-Distance Journey", brief: "Create an interactive migration story or simulation that includes route hazards, rest points, and one adaptation that helps the animal travel.", features: ["mapped route with stages", "one environmental hazard", "one helpful adaptation", "a clear arrival and explanation"] },
    ],
    challenge: { title: "Change One Variable", brief: "Change group size, speed, spacing distance, or obstacle number and compare two runs using the same observation method.", steps: ["Choose one variable only.", "Record the first run.", "Change the variable and record the second run."], checks: ["only one planned variable changes", "both runs use the same measure", "the conclusion matches the evidence"] },
    quiz: [
      q("What is a model?", ["a simplified representation", "a perfect copy", "a password", "only a costume"], "a simplified representation", "models leave out detail to explore selected rules."),
      q("What does distance sensing measure?", ["separation between objects", "sound speed", "file size", "quiz score only"], "separation between objects", "distance reports how far apart sprites are."),
      q("Why start with two sprites?", ["to test the rule clearly", "to remove movement", "to avoid saving", "to change the editor"], "to test the rule clearly", "fewer interacting parts make bugs easier to see."),
      q("What is migration?", ["regular movement between regions", "one costume change", "a random click", "a score reset"], "regular movement between regions", "many animals travel seasonally for food, breeding, or climate."),
      q("How should model results be described?", ["as evidence with limitations", "as guaranteed reality", "without rules", "using private data"], "as evidence with limitations", "simplified rules cannot capture every real factor."),
    ],
  },
  {
    title: "Module 9 - Build, Test, Improve",
    focus: "engineering design, fair testing, measurements, variables, comparison, and iteration",
    outcome: "a Scratch investigation that records evidence from two designs and supports a justified improvement",
    introduction: "Engineers rarely choose the first idea without testing it. You will define a fair comparison, record measurements, and use evidence to improve a design.",
    concepts: [["prototype", "is an early version built for testing"], ["variable", "is a factor that can change"], ["fair test", "changes one planned factor while keeping others consistent"], ["iteration", "means build, test, improve, and repeat"]],
    algorithm: ["Define the design question.", "Choose the factor to change and the result to measure.", "Keep other test conditions consistent.", "Record results from the first design.", "Test the changed design in the same way.", "Compare evidence and recommend an improvement."],
    steam: "engineering, forces, flight, landing, measurement, and evidence-based design",
    predict: "Why is it difficult to know what improved a design if wing size, paper type, and launch force all change together?",
    misconception: "The design with the single longest result is not automatically best; repeated trials and consistent measurement are more reliable.",
    debugging: "Check that every trial resets values and that the program records the same measure in the same unit.",
    support: "Use teacher-provided measurements if physical materials are unavailable, then focus on recording and comparison.",
    discussion: {
      prompt: "Engineers balance performance, safety, cost, materials, and user needs. Discuss why the fastest or longest-travelling design may not be the best design.",
      questions: ["What makes a test fair?", "How many trials give more confidence?", "Which design needs matter besides speed or distance?"],
    },
    practice: {
      title: "Digital Test Recorder",
      brief: "Build a Scratch recorder that asks for a design name and three measurements, then reports the total or average.",
      steps: ["Create variables for trial results.", "Ask for three measurements.", "Calculate and display a summary."],
      checks: ["three results are captured", "the calculation is correct", "a new test resets old values"],
    },
    projects: [
      { title: "Paper Aircraft Investigation", brief: "Compare two paper aircraft, glider, or helicopter designs using safe classroom trials or supplied data and present the evidence in Scratch.", features: ["one planned design variable", "at least three trials per design", "consistent units and launch rules", "an evidence-based recommendation"] },
      { title: "Landing Design Challenge", brief: "Design a digital or physical landing system for a fictional rover or payload and use Scratch to record drop, accuracy, or stability tests.", features: ["clear landing success criteria", "two prototype versions", "recorded comparable tests", "one justified improvement"] },
    ],
    challenge: { title: "Visual Results", brief: "Turn the recorded measurements into a simple bar chart, animated comparison, or result dashboard.", steps: ["Choose a consistent scale.", "Draw or size bars from values.", "Label both designs and units."], checks: ["visual matches the data", "labels and units are clear", "the chart does not exaggerate differences"] },
    quiz: [
      q("What is a prototype?", ["an early test version", "a final certificate", "a private password", "a quiz hint"], "an early test version", "prototypes reveal problems before final decisions."),
      q("What does a fair test change?", ["one planned factor", "every condition", "no measurable result", "the rules after each trial"], "one planned factor", "changing one factor helps explain the cause of a difference."),
      q("Why repeat trials?", ["to reduce the effect of unusual results", "to guarantee success", "to hide data", "to change units"], "to reduce the effect of unusual results", "several measurements show whether a pattern is consistent."),
      q("What is iteration?", ["test and improve repeatedly", "save only once", "avoid feedback", "copy without testing"], "test and improve repeatedly", "engineering designs develop through evidence-based cycles."),
      q("What makes a recommendation strong?", ["it refers to recorded evidence", "it uses the loudest opinion", "it ignores units", "it changes the question"], "it refers to recorded evidence", "claims should be supported by the measured results."),
    ],
  },
  {
    title: "Module 10 - Explorer Showcase",
    focus: "project planning, decomposition, debugging, user testing, presentation, and reflection",
    outcome: "an original polished Scratch project and portfolio explanation showing growth across the Explorer course",
    introduction: "The showcase is your opportunity to combine skills around an idea you care about. A smaller reliable project with clear explanation is stronger than a huge unfinished one.",
    concepts: [["decomposition", "breaks a large task into smaller parts"], ["feature", "is one useful behavior in a project"], ["user test", "observes another person trying the project"], ["portfolio", "collects work and evidence of learning"]],
    algorithm: ["Choose a safe goal and intended user.", "List the smallest features needed.", "Plan sprites, data, scenes, and controls.", "Build the minimum working version.", "Test with success checks and another user.", "Improve, save, submit, and present the project."],
    steam: "creative design, communication, computing, self-evaluation, and presentation",
    predict: "Which feature must work first to prove the main idea of your chosen project?",
    misconception: "Adding many features does not automatically improve a project; reliability, clarity, and purposeful design matter more.",
    debugging: "Keep a short bug log with the symptom, test, cause, change, and result instead of changing many blocks at once.",
    support: "Remix and improve a previous module project with a new purpose, feature, or audience.",
    discussion: {
      prompt: "Creators make choices about audience, purpose, accessibility, and safety. Discuss what responsibility a creator has when another person uses the project.",
      questions: ["Who is the intended user?", "How will the user know what to do?", "What evidence will show the project is ready?"],
    },
    practice: {
      title: "Project Proposal and Test Plan",
      brief: "Prepare a one-page plan naming the goal, user, features, algorithm, assets, success checks, and safe information rules.",
      steps: ["Write the goal and intended user.", "List must-have and optional features.", "Draw the main algorithm and define four tests."],
      checks: ["goal and user are specific", "must-have features fit the time", "tests match the promised behavior"],
    },
    projects: [
      { title: "Remix and Transform", brief: "Choose an earlier Explorer project and transform its purpose, audience, rules, or presentation so the result demonstrates substantial new thinking.", features: ["original work is identified", "at least two meaningful improvements", "all required behavior remains reliable", "testing evidence compares before and after"] },
      { title: "Original Explorer Project", brief: "Create an original story, game, animation, art tool, quiz, nature model, or engineering investigation that combines at least four Explorer concepts.", features: ["clear user and purpose", "four connected coding concepts", "instructions and feedback", "peer testing leads to improvement"] },
    ],
    challenge: { title: "Teach Another Learner", brief: "Create a short built-in tutorial, help screen, poster, or demonstration that teaches one important feature of the project.", steps: ["Choose one feature learners may find difficult.", "Explain it with steps and an example.", "Test the explanation with another learner."], checks: ["instructions are accurate", "the learner can follow them", "private information is absent"] },
    quiz: [
      q("What is decomposition?", ["breaking a task into smaller parts", "adding every feature at once", "deleting the plan", "hiding instructions"], "breaking a task into smaller parts", "small parts are easier to build and test."),
      q("What is a minimum working version?", ["the smallest build proving the main idea", "the final project with every feature", "a copied screenshot", "an empty Stage"], "the smallest build proving the main idea", "it provides a reliable base for later improvements."),
      q("What can a user test reveal?", ["confusing controls and missing feedback", "the user's password", "a guaranteed grade", "the exact future"], "confusing controls and missing feedback", "another user notices assumptions the creator may miss."),
      q("What belongs in a portfolio explanation?", ["goal, choices, tests, and improvements", "private contact details", "only the file name", "unverified claims"], "goal, choices, tests, and improvements", "evidence shows how learning developed."),
      q("What makes a project showcase-ready?", ["reliable behavior and clear explanation", "the largest number of sprites", "public sharing without approval", "no testing"], "reliable behavior and clear explanation", "quality is demonstrated by working evidence and thoughtful communication."),
    ],
  },
];
