module.exports = [
  {
    title: "Interactive Story Studio",
    focus: "events, sequences, coordinates, timing, and broadcast messages",
    outcome: "a three-scene interactive story with a meaningful user choice",
    concepts: [
      ["event", "starts a script when something happens"],
      ["sequence", "puts instructions in the order Scratch should follow"],
      ["coordinates", "describe a sprite's horizontal x and vertical y position"],
      ["broadcast", "sends a message that other sprites and the Stage can receive"],
    ],
    algorithm: [
      "Start when the green flag is clicked.",
      "Introduce the setting and the first character.",
      "Broadcast a message to change to the next scene.",
      "Wait for each line of dialogue to finish.",
      "Ask the learner to choose what the character should do.",
      "Use the answer to select an ending, then show a clear finish.",
    ],
    practice: "Coordinate a short conversation between two sprites without their speech overlapping.",
    project: "Create a three-scene interactive story in which the viewer makes one choice that changes what happens.",
    challenge: "Add a second ending and a replay button so the viewer can explore both choices.",
    projectChecks: ["three clear scenes", "two or more characters", "one user choice", "broadcasts coordinate scene changes", "a clear ending"],
    misconception: "A broadcast does not pause the sender unless the broadcast-and-wait block is used.",
    questions: [
      ["Which block can tell several sprites that a new scene has started?", ["broadcast", "move 10 steps", "change color", "pen down"], "broadcast"],
      ["What does a sequence describe?", ["instructions in order", "a sprite costume", "a sound volume", "a random number"], "instructions in order"],
      ["Which coordinate changes when a sprite moves left or right?", ["x", "y", "size", "direction only"], "x"],
      ["Why use wait blocks during dialogue?", ["to stop lines overlapping", "to erase sprites", "to rename variables", "to save the file"], "to stop lines overlapping"],
      ["What makes a story interactive?", ["the viewer can affect it", "it has one backdrop", "it has no events", "every sprite stays still"], "the viewer can affect it"],
    ],
    intro: "Welcome to the course. You will build ten projects. Open each lesson in order, read the overview and visual guide, plan the algorithm, then complete the guided practice before the main project. Complete the five quiz questions, submit your answers, read each explanation, and retry when needed until you reach 80 percent. Use hints, test often, reflect, and upload your work. Open Scratch in a browser or the desktop app. Use File > Save to your computer to download a .sb3 file. Give projects safe names and never place your full name, password, address, phone number, school timetable, or other private information inside them. Mistakes are useful clues: test one small change, read the hint, ask for help, and try again.",
  },
  {
    title: "Maze Game Designer",
    focus: "keyboard input, movement, sensing, conditionals, and coordinates",
    outcome: "a maze game with reliable wall collision, a goal, and restart behavior",
    concepts: [
      ["keyboard input", "lets the player control a sprite with keys"],
      ["condition", "asks a yes-or-no question before choosing an action"],
      ["sensing", "checks contact, color, distance, or another changing fact"],
      ["collision", "happens when game objects touch"],
    ],
    algorithm: ["Read an arrow key.", "Move the player a small distance.", "Check whether the player touches a wall.", "Undo an invalid move.", "Check whether the player reaches the goal.", "Show success or reset the level."],
    practice: "Move a player with the arrow keys and make wall contact push the player back.",
    project: "Build a maze game with a start point, a goal, wall collision, and a dependable restart action.",
    challenge: "Add a timer, hazards, or a second level that becomes available after the first goal.",
    projectChecks: ["four arrow keys work", "walls cannot be crossed", "goal gives feedback", "restart returns to the start", "instructions are visible"],
    misconception: "A large movement step can jump through thin walls; smaller steps make collision checks more dependable.",
    questions: [
      ["What should happen immediately after moving in a maze?", ["check for wall contact", "delete the Stage", "hide every sprite", "stop reading keys"], "check for wall contact"],
      ["Which block shape makes a decision?", ["if", "say", "wait", "set x"], "if"],
      ["Why undo a move after touching a wall?", ["to keep the player outside the wall", "to add a costume", "to start music", "to rename the project"], "to keep the player outside the wall"],
      ["Which sensing fact can detect a colored maze wall?", ["touching color", "username", "loudness only", "days since 2000"], "touching color"],
      ["What should a restart script reset?", ["the player's position and game state", "only the sprite name", "the Scratch language", "the computer clock"], "the player's position and game state"],
    ],
  },
  {
    title: "Catch and Score",
    focus: "variables, random positions, loops, scoring, and game rules",
    outcome: "a timed catching game with score changes and clear feedback",
    concepts: [
      ["variable", "stores a value that can change while a project runs"],
      ["random", "chooses an unpredictable value inside a set range"],
      ["loop", "repeats instructions"],
      ["game rule", "explains what changes and how a player succeeds"],
    ],
    algorithm: ["Reset the score and timer.", "Place a collectible at a random position.", "Move the collectible.", "Check for a catch or a miss.", "Update the score and give feedback.", "Repeat until time ends, then show the result."],
    practice: "Make one collectible jump to random positions and increase a score when clicked or caught.",
    project: "Build a timed catching game with a score, moving or falling objects, and feedback for catches and misses.",
    challenge: "Add bonus and penalty objects with different point values and fair spawn rules.",
    projectChecks: ["score resets at the start", "objects appear unpredictably", "catches change score", "time or round ending works", "final feedback explains the result"],
    misconception: "A variable should be reset at the beginning or an old value may carry into a new round.",
    questions: [
      ["What does a score variable store?", ["a changing number", "a costume picture", "a block category", "a keyboard key"], "a changing number"],
      ["When should the score be reset?", ["at the start of each round", "after every point", "only when editing", "never"], "at the start of each round"],
      ["Why use a random position?", ["to make catches less predictable", "to remove all rules", "to stop the timer", "to lock the sprite"], "to make catches less predictable"],
      ["Which structure repeats the game actions?", ["loop", "costume", "backdrop", "comment"], "loop"],
      ["What makes scoring fair?", ["rules stay clear and consistent", "points change secretly", "objects cannot be reached", "the score never displays"], "rules stay clear and consistent"],
    ],
  },
  {
    title: "Clone Attack",
    focus: "clones, repeated behavior, spawn control, collision, and difficulty",
    outcome: "an avoid-or-defend game with independently behaving clones",
    concepts: [
      ["clone", "is a temporary copy of a sprite created while a project runs"],
      ["spawn", "means create a game object at a chosen time and place"],
      ["clone script", "starts only for each newly created clone"],
      ["difficulty", "controls how demanding a game becomes"],
    ],
    algorithm: ["Create enemies at controlled intervals.", "Give each clone a starting position.", "Run movement rules for that clone.", "Check collision with the player or defense.", "Change lives or score.", "Delete finished clones and gradually adjust difficulty."],
    practice: "Create several clones that start in different places, move independently, and delete themselves.",
    project: "Create an avoid-or-defend game that uses clones, collision rules, lives or score, and increasing difficulty.",
    challenge: "Add two enemy types with different speeds, costumes, or movement behavior.",
    projectChecks: ["clones spawn at intervals", "each clone moves independently", "collision changes game state", "clones are deleted when finished", "difficulty changes fairly"],
    misconception: "Code under the green flag controls the original sprite; clone behavior belongs under when-I-start-as-a-clone.",
    questions: [
      ["What is a clone?", ["a temporary sprite copy", "a saved .sb3 file", "a sound effect", "a quiz answer"], "a temporary sprite copy"],
      ["Which event begins a clone's own behavior?", ["when I start as a clone", "when backdrop switches only", "when space key released", "when timer equals zero only"], "when I start as a clone"],
      ["Why delete clones that leave the play area?", ["to avoid unused objects building up", "to increase file names", "to stop all broadcasts", "to erase the original sprite"], "to avoid unused objects building up"],
      ["What controls spawn rate?", ["the delay between creating clones", "the sprite name", "the pen color", "the question text"], "the delay between creating clones"],
      ["How can difficulty rise fairly?", ["change one rule gradually", "make winning impossible at once", "hide all instructions", "remove player controls"], "change one rule gradually"],
    ],
  },
  {
    title: "Quiz Show Challenge",
    focus: "questions, answers, conditionals, variables, validation, and feedback",
    outcome: "a five-question interactive quiz that scores answers and explains results",
    concepts: [
      ["answer", "stores the latest text entered into an ask block"],
      ["validation", "checks whether input follows the rule you expect"],
      ["feedback", "tells the player what happened and how to improve"],
      ["score", "records progress through the quiz"],
    ],
    algorithm: ["Ask a question.", "Read and check the answer.", "Give correct or try-again feedback.", "Update the score when appropriate.", "Move to the next question.", "Show a useful final result after question five."],
    practice: "Build one question that responds differently to correct and incorrect answers.",
    project: "Create a five-question interactive quiz with scoring, friendly feedback, and a final result.",
    challenge: "Use a list as a question bank or add a visible countdown for each question.",
    projectChecks: ["five questions are included", "answers are checked", "score changes correctly", "feedback is kind and useful", "final result is shown"],
    misconception: "The answer reporter changes after every ask block, so check it before asking the next question.",
    questions: [
      ["Where does Scratch keep text typed after an ask block?", ["answer", "mouse x", "costume number", "timer only"], "answer"],
      ["What does validation do?", ["checks input against a rule", "draws a backdrop", "duplicates a sprite", "changes the editor language"], "checks input against a rule"],
      ["When should a quiz score increase?", ["after a correct answer", "before every question", "after every answer", "only when the flag is clicked"], "after a correct answer"],
      ["What is useful feedback?", ["clear and kind information", "a secret rule", "no response", "an unrelated sound only"], "clear and kind information"],
      ["Why show a final result?", ["to summarize the player's progress", "to erase the questions", "to disable saving", "to change coordinates"], "to summarize the player's progress"],
    ],
  },
  {
    title: "Animation and Music Lab",
    focus: "costumes, sound, timing, parallel scripts, and synchronization",
    outcome: "a short animated music or dance performance whose parts stay synchronized",
    concepts: [
      ["costume", "is one visual pose or appearance for a sprite"],
      ["parallel scripts", "run at the same time"],
      ["synchronization", "keeps separate actions working together"],
      ["cue", "is a signal that tells a performer when to act"],
    ],
    algorithm: ["Start the music.", "Begin performer scripts together.", "Broadcast cues for important moments.", "Synchronize costume, movement, and backdrop changes.", "Check timing after each scene.", "Finish the sound and visuals together."],
    practice: "Synchronize a sprite's movement and costume changes with a short sound beat.",
    project: "Produce a short animated music, dance, or rhythm performance with coordinated scenes.",
    challenge: "Add camera-style scene changes or an interactive control that remixes part of the performance.",
    projectChecks: ["sound is intentional", "costumes create animation", "two actions run in parallel", "broadcast cues keep timing clear", "performance has a planned ending"],
    misconception: "Scripts starting together may drift if their waits differ, so shared broadcast cues can resynchronize them.",
    questions: [
      ["What creates sprite animation?", ["changing costumes over time", "renaming the Stage", "deleting all sounds", "using one still image only"], "changing costumes over time"],
      ["What are parallel scripts?", ["scripts running at the same time", "blocks stored in a list", "two saved files", "questions with four options"], "scripts running at the same time"],
      ["What can coordinate several performers?", ["broadcast cues", "random usernames", "the eraser tool only", "a hidden score"], "broadcast cues"],
      ["Why test timing in small sections?", ["to find where actions drift", "to make the file larger", "to remove every wait", "to avoid listening"], "to find where actions drift"],
      ["What makes an ending feel planned?", ["sound and visuals finish together", "sprites stop at random", "the project never stops", "instructions disappear first"], "sound and visuals finish together"],
    ],
  },
  {
    title: "Smart Pet Simulator",
    focus: "state, variables, decisions, gradual change, and simulation rules",
    outcome: "a virtual pet whose needs change and whose reactions follow clear rules",
    concepts: [
      ["state", "describes what an object is like right now"],
      ["simulation", "uses rules to model a real or imagined system"],
      ["boundary", "is a minimum or maximum a value should not cross"],
      ["decision", "selects a reaction based on current information"],
    ],
    algorithm: ["Set starting hunger and happiness.", "Read a player action.", "Change the pet's state over time.", "Choose a reaction using conditions.", "Keep values inside valid boundaries.", "Repeat and give the player clear feedback."],
    practice: "Change a sprite's mood, costume, or message when one need variable becomes high or low.",
    project: "Build a virtual pet with at least two needs, several player actions, and reactions that match its state.",
    challenge: "Add day and night, health, or a progress record similar to a high score.",
    projectChecks: ["two need variables are visible or explained", "needs change over time", "player actions affect needs", "pet reactions match its state", "values stay within sensible boundaries"],
    misconception: "Without minimum and maximum checks, a need such as hunger can become less than zero or grow forever.",
    questions: [
      ["What does state describe?", ["what something is like now", "only its file name", "the editor color", "a future quiz"], "what something is like now"],
      ["Why use variables in a pet simulator?", ["to store changing needs", "to paint costumes", "to upload files", "to rename blocks"], "to store changing needs"],
      ["What is a boundary rule?", ["a limit a value should not cross", "a random costume", "a sound library", "a public username"], "a limit a value should not cross"],
      ["Which structure selects a pet reaction?", ["condition", "comment", "backpack", "paintbrush"], "condition"],
      ["What makes a simulation understandable?", ["clear rules and visible feedback", "hidden controls", "values with no meaning", "unrelated actions"], "clear rules and visible feedback"],
    ],
  },
  {
    title: "Drawing Machine",
    focus: "pen tools, loops, angles, custom blocks, and parameters",
    outcome: "an interactive geometric art generator built from reusable drawing instructions",
    concepts: [
      ["custom block", "groups reusable instructions under a name"],
      ["parameter", "passes a value into a custom block"],
      ["angle", "measures the amount of turn"],
      ["polygon", "is a closed shape made from straight sides"],
    ],
    algorithm: ["Clear the Stage.", "Choose the number of sides and side length.", "Put the pen down.", "Repeat moving and turning.", "Change color, size, or position.", "Call the drawing block again to build a pattern."],
    practice: "Create a custom block with parameters that draws a polygon.",
    project: "Build an interactive geometric art generator using pen tools, loops, and at least one custom block.",
    challenge: "Create spirals or let the user control sides, size, turn, and color.",
    projectChecks: ["Stage clears before drawing", "loop draws repeated sides", "turn angle creates a planned shape", "custom block is reused", "user can change part of the pattern"],
    misconception: "For a regular polygon, the outside turn is 360 divided by the number of sides.",
    questions: [
      ["Why create a custom block?", ["to reuse a group of instructions", "to upload a sound", "to hide the Stage", "to answer a quiz automatically"], "to reuse a group of instructions"],
      ["What does a parameter do?", ["supplies a changeable value", "deletes a variable", "starts the computer", "locks the pen"], "supplies a changeable value"],
      ["What turn draws a square in a repeat four loop?", ["90 degrees", "45 degrees", "60 degrees", "120 degrees"], "90 degrees"],
      ["Why clear before drawing again?", ["to remove the previous picture", "to increase score", "to clone the sprite", "to save private data"], "to remove the previous picture"],
      ["What creates a pattern?", ["repeated shapes with planned changes", "one accidental dot", "no pen movement", "an unanswered ask block"], "repeated shapes with planned changes"],
    ],
  },
  {
    title: "Eco-System Simulation",
    focus: "modeling, probability, clones or lists, rules, and observation",
    outcome: "a simple ecosystem or real-world process simulation with observable change",
    concepts: [
      ["model", "is a simplified representation used to explore an idea"],
      ["probability", "describes how likely an event is"],
      ["organism", "is a living thing represented in the simulation"],
      ["observation", "records what happens without changing the rules"],
    ],
    algorithm: ["Create the starting organisms.", "Apply movement and survival rules.", "Check access to food or suitable weather.", "Reproduce only under the chosen conditions.", "Remove organisms when survival conditions fail.", "Report changes and compare repeated runs."],
    practice: "Simulate one creature responding to food, weather, or another environmental condition.",
    project: "Create a simple ecosystem or real-world process simulation with rules that produce visible change over time.",
    challenge: "Add a controllable environmental variable, run two trials, and compare the outcomes.",
    projectChecks: ["model has a clear question", "organisms follow stated rules", "chance is used carefully", "change can be observed", "results are explained as a model, not a perfect prediction"],
    misconception: "A model is useful without being exact; its limits should be explained instead of hidden.",
    questions: [
      ["What is a model?", ["a simplified representation", "a perfect copy of reality", "only a costume", "a password"], "a simplified representation"],
      ["What does probability describe?", ["how likely something is", "a sprite's x position only", "the file size", "the sound volume only"], "how likely something is"],
      ["Why repeat a simulation?", ["to compare possible outcomes", "to guarantee one result", "to remove all rules", "to avoid observing"], "to compare possible outcomes"],
      ["What should happen when survival conditions fail?", ["apply the planned removal or change rule", "invent a secret rule", "always add score", "ignore every variable"], "apply the planned removal or change rule"],
      ["How should results be described?", ["as evidence from a simplified model", "as a guaranteed future", "without mentioning rules", "using private information"], "as evidence from a simplified model"],
    ],
  },
  {
    title: "Portfolio Capstone",
    focus: "decomposition, planning, iteration, debugging, user testing, and presentation",
    outcome: "an original polished Scratch project combining at least four intermediate concepts",
    concepts: [
      ["decomposition", "breaks a large problem into smaller manageable parts"],
      ["minimum version", "is the smallest build that proves the main idea works"],
      ["iteration", "means test, improve, and repeat"],
      ["user testing", "observes another person trying the project"],
    ],
    algorithm: ["Choose a safe problem or creative goal.", "Define the user and what success means.", "Split the project into features.", "Plan scripts, sprites, data, and tests.", "Build and debug the minimum version.", "Collect user feedback, improve, and present the final project."],
    practice: "Produce a project proposal, flowchart, sprite list, feature list, and test plan before building.",
    project: "Create an original polished game, animation, quiz, story, or simulation that combines at least four intermediate concepts.",
    challenge: "Add accessibility options, multiple levels, or an advanced feature and explain why it improves the project.",
    projectChecks: ["goal and audience are clear", "four intermediate concepts are combined", "minimum version works", "testing leads to improvements", "presentation explains important design decisions"],
    misconception: "A capstone does not need every possible feature; a smaller polished project is stronger than a large unfinished one.",
    questions: [
      ["What is decomposition?", ["breaking a problem into smaller parts", "joining every script together", "skipping planning", "using one giant block"], "breaking a problem into smaller parts"],
      ["Why build a minimum version first?", ["to prove the main idea works", "to avoid all improvements", "to make the project public", "to remove testing"], "to prove the main idea works"],
      ["What is iteration?", ["testing and improving repeatedly", "saving only once", "choosing a sprite", "answering without feedback"], "testing and improving repeatedly"],
      ["What can user testing reveal?", ["confusing controls and useful improvements", "the user's password", "a guaranteed score", "the exact future"], "confusing controls and useful improvements"],
      ["What should a capstone presentation explain?", ["the goal, choices, testing, and improvements", "private information", "only the file name", "nothing about the code"], "the goal, choices, testing, and improvements"],
    ],
  },
];
